"""Nordic place records and service phrases."""

from __future__ import annotations

PLACES = [
    # Norway — main cities, towns, regions, fjords, islands and attractions
    {"country": "Norway", "canonical": "Oslo", "kind": "city", "aliases": ["Oslo City"]},
    {"country": "Norway", "canonical": "Bergen", "kind": "city", "aliases": ["Bergent"]},
    {"country": "Norway", "canonical": "Tromsø", "kind": "city", "aliases": ["Tromso", "Tromsoe"]},
    {"country": "Norway", "canonical": "Trondheim", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Stavanger", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Ålesund", "kind": "city", "aliases": ["Alesund", "Aalesund"]},
    {"country": "Norway", "canonical": "Bodø", "kind": "city", "aliases": ["Bodo", "Bodoe"]},
    {"country": "Norway", "canonical": "Narvik", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Alta", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Kirkenes", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Honningsvåg", "kind": "town", "aliases": ["Honningsvag"]},
    {"country": "Norway", "canonical": "Longyearbyen", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Svolvær", "kind": "town", "aliases": ["Svolvaer", "Svolaver", "Svoalvaer", "Svolvaerr"]},
    {"country": "Norway", "canonical": "Leknes", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Reine", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Hamnøy", "kind": "village", "aliases": ["Hamnoy"]},
    {"country": "Norway", "canonical": "Nusfjord", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Flåm", "kind": "village", "aliases": ["Flam"]},
    {"country": "Norway", "canonical": "Myrdal", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Voss", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Gudvangen", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Geiranger", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Åndalsnes", "kind": "town", "aliases": ["Andalsnes"]},
    {"country": "Norway", "canonical": "Molde", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Kristiansand", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Tønsberg", "kind": "city", "aliases": ["Tonsberg"]},
    {"country": "Norway", "canonical": "Drammen", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Fredrikstad", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Lillehammer", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Lofoten", "kind": "region", "aliases": ["Lofoten Islands"]},
    {"country": "Norway", "canonical": "Senja", "kind": "island", "aliases": []},
    {"country": "Norway", "canonical": "Vesterålen", "kind": "region", "aliases": ["Vesteralen"]},
    {"country": "Norway", "canonical": "North Cape", "kind": "attraction", "aliases": ["Nordkapp", "North Cape Norway"]},
    {"country": "Norway", "canonical": "Svalbard", "kind": "region", "aliases": []},
    {"country": "Norway", "canonical": "Oslofjord", "kind": "fjord", "aliases": ["Oslo Fjord"]},
    {"country": "Norway", "canonical": "Sognefjord", "kind": "fjord", "aliases": []},
    {"country": "Norway", "canonical": "Nærøyfjord", "kind": "fjord", "aliases": ["Naeroyfjord", "Nærøyfjorden", "Naeroyfjorden"]},
    {"country": "Norway", "canonical": "Aurlandsfjord", "kind": "fjord", "aliases": []},
    {"country": "Norway", "canonical": "Hardangerfjord", "kind": "fjord", "aliases": []},
    {"country": "Norway", "canonical": "Geirangerfjord", "kind": "fjord", "aliases": ["Geirangerfjorden"]},
    {"country": "Norway", "canonical": "Lysefjord", "kind": "fjord", "aliases": ["Lysefjorden"]},
    {"country": "Norway", "canonical": "Trollfjord", "kind": "fjord", "aliases": ["Trollfjorden"]},
    {"country": "Norway", "canonical": "Preikestolen", "kind": "attraction", "aliases": ["Pulpit Rock"]},
    {"country": "Norway", "canonical": "Kjerag", "kind": "attraction", "aliases": ["Kjeragbolten"]},
    {"country": "Norway", "canonical": "Trolltunga", "kind": "attraction", "aliases": []},
    {"country": "Norway", "canonical": "Bryggen", "kind": "attraction", "aliases": []},
    {"country": "Norway", "canonical": "Fløibanen", "kind": "attraction", "aliases": ["Floibanen", "Fløien"]},
    {"country": "Norway", "canonical": "Mount Fløyen", "kind": "attraction", "aliases": ["Mt Fløyen", "Mt Floyen", "Mount Floyen", "Fløyen", "Floyen"]},
    {"country": "Norway", "canonical": "Fjellheisen", "kind": "attraction", "aliases": []},
    {"country": "Norway", "canonical": "Flåm Railway", "kind": "route", "aliases": ["Flam Railway", "Flåmsbana", "Flamsbana"]},
    {"country": "Norway", "canonical": "Norway in a Nutshell", "kind": "route", "aliases": ["Norway in a NUtshell", "Norway in a Nutsheel", "Norway in a Nutshel", "Norway in a NUtsheel"]},
    {"country": "Norway", "canonical": "Atlantic Road", "kind": "route", "aliases": ["Atlanterhavsveien", "Atlantic Ocean Road"]},
    {"country": "Norway", "canonical": "Oslo Airport", "kind": "airport", "aliases": ["Oslo Gardermoen", "Gardermoen Airport", "OSL"]},
    {"country": "Norway", "canonical": "Bergen Airport", "kind": "airport", "aliases": ["Bergen Flesland", "Flesland Airport", "BGO"]},
    {"country": "Norway", "canonical": "Tromsø Airport", "kind": "airport", "aliases": ["Tromso Airport", "Tromsoe Airport", "TOS"]},
    {"country": "Norway", "canonical": "Svolvær Airport", "kind": "airport", "aliases": ["Svolvaer Airport", "Svolaver Airport", "SVJ"]},
    {"country": "Norway", "canonical": "Bodø Airport", "kind": "airport", "aliases": ["Bodo Airport", "Bodoe Airport", "BOO"]},
    {"country": "Norway", "canonical": "Kirkenes Airport", "kind": "airport", "aliases": ["KKN"]},

    # Norway — expanded itinerary destinations, fjord hubs, resorts, rail hubs and cruise ports
    {"country": "Norway", "canonical": "Hamar", "kind": "town", "aliases": ["Mjøsbyen Hamar"]},
    {"country": "Norway", "canonical": "Gjøvik", "kind": "town", "aliases": ["Gjovik"]},
    {"country": "Norway", "canonical": "Kongsvinger", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Eidsvoll", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Lillestrøm", "kind": "city", "aliases": ["Lillestrom"]},
    {"country": "Norway", "canonical": "Moss", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Sarpsborg", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Halden", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Horten", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Larvik", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Sandefjord", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Porsgrunn", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Skien", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Notodden", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Rjukan", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Kragerø", "kind": "town", "aliases": ["Kragero"]},
    {"country": "Norway", "canonical": "Risør", "kind": "town", "aliases": ["Risor"]},
    {"country": "Norway", "canonical": "Arendal", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Grimstad", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Lillesand", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Mandal", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Flekkefjord", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Farsund", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Lyngdal", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Evje", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Setesdal", "kind": "region", "aliases": []},
    {"country": "Norway", "canonical": "Hovden", "kind": "resort", "aliases": ["Hovden i Setesdal"]},
    {"country": "Norway", "canonical": "Sandnes", "kind": "city", "aliases": []},
    {"country": "Norway", "canonical": "Sola", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Egersund", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Haugesund", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Kopervik", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Skudeneshavn", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Utsira", "kind": "island", "aliases": []},
    {"country": "Norway", "canonical": "Ryfylke", "kind": "region", "aliases": []},
    {"country": "Norway", "canonical": "Sauda", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Jørpeland", "kind": "town", "aliases": ["Jorpeland"]},
    {"country": "Norway", "canonical": "Tau", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Odda", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Eidfjord", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Ulvik", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Norheimsund", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Rosendal", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Balestrand", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Lærdal", "kind": "village", "aliases": ["Laerdal"]},
    {"country": "Norway", "canonical": "Aurland", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Undredal", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Solvorn", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Kaupanger", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Finse", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Geilo", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Gol", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Hemsedal", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Beitostølen", "kind": "resort", "aliases": ["Beitostolen"]},
    {"country": "Norway", "canonical": "Fagernes", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Loen", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Olden", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Stryn", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Nordfjordeid", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Førde", "kind": "town", "aliases": ["Forde"]},
    {"country": "Norway", "canonical": "Florø", "kind": "town", "aliases": ["Floro"]},
    {"country": "Norway", "canonical": "Måløy", "kind": "town", "aliases": ["Maloy"]},
    {"country": "Norway", "canonical": "Kalvåg", "kind": "village", "aliases": ["Kalvag"]},
    {"country": "Norway", "canonical": "Stord", "kind": "island", "aliases": []},
    {"country": "Norway", "canonical": "Bømlo", "kind": "island", "aliases": ["Bomlo"]},
    {"country": "Norway", "canonical": "Fedje", "kind": "island", "aliases": []},
    {"country": "Norway", "canonical": "Austevoll", "kind": "island", "aliases": []},
    {"country": "Norway", "canonical": "Kristiansund", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Hellesylt", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Valldal", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Trollstigen", "kind": "route", "aliases": ["Trollstigen Road"]},
    {"country": "Norway", "canonical": "Sunndalsøra", "kind": "town", "aliases": ["Sunndalsora"]},
    {"country": "Norway", "canonical": "Surnadal", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Hjørundfjord", "kind": "fjord", "aliases": ["Hjorundfjord"]},
    {"country": "Norway", "canonical": "Romsdalen", "kind": "region", "aliases": []},
    {"country": "Norway", "canonical": "Røros", "kind": "town", "aliases": ["Roros"]},
    {"country": "Norway", "canonical": "Oppdal", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Stjørdal", "kind": "town", "aliases": ["Stjordal"]},
    {"country": "Norway", "canonical": "Levanger", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Steinkjer", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Namsos", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Orkanger", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Dombås", "kind": "town", "aliases": ["Dombas"]},
    {"country": "Norway", "canonical": "Otta", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Lom", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Vågå", "kind": "village", "aliases": ["Vaga"]},
    {"country": "Norway", "canonical": "Jotunheimen", "kind": "national_park", "aliases": ["Jotunheimen National Park"]},
    {"country": "Norway", "canonical": "Rondane", "kind": "national_park", "aliases": ["Rondane National Park"]},
    {"country": "Norway", "canonical": "Dovrefjell", "kind": "national_park", "aliases": ["Dovrefjell National Park"]},
    {"country": "Norway", "canonical": "Hardangervidda", "kind": "national_park", "aliases": ["Hardangervidda National Park"]},
    {"country": "Norway", "canonical": "Jostedalsbreen", "kind": "national_park", "aliases": ["Jostedalsbreen National Park"]},
    {"country": "Norway", "canonical": "Folgefonna", "kind": "national_park", "aliases": ["Folgefonna National Park"]},
    {"country": "Norway", "canonical": "Trysil", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Hafjell", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Kvitfjell", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Norefjell", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Rauland", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Gaustablikk", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Myrkdalen", "kind": "resort", "aliases": []},
    {"country": "Norway", "canonical": "Vrådal", "kind": "resort", "aliases": ["Vradal"]},
    {"country": "Norway", "canonical": "Brønnøysund", "kind": "town", "aliases": ["Bronnoysund"]},
    {"country": "Norway", "canonical": "Sandnessjøen", "kind": "town", "aliases": ["Sandnessjoen"]},
    {"country": "Norway", "canonical": "Mosjøen", "kind": "town", "aliases": ["Mosjoen"]},
    {"country": "Norway", "canonical": "Mo i Rana", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Fauske", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Rognan", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Saltstraumen", "kind": "attraction", "aliases": []},
    {"country": "Norway", "canonical": "Kjerringøy", "kind": "village", "aliases": ["Kjerringoy"]},
    {"country": "Norway", "canonical": "Vega", "kind": "island", "aliases": ["Vega Islands"]},
    {"country": "Norway", "canonical": "Lovund", "kind": "island", "aliases": []},
    {"country": "Norway", "canonical": "Træna", "kind": "island", "aliases": ["Traena"]},
    {"country": "Norway", "canonical": "Dønna", "kind": "island", "aliases": ["Donna"]},
    {"country": "Norway", "canonical": "Henningsvær", "kind": "village", "aliases": ["Henningsvaer"]},
    {"country": "Norway", "canonical": "Kabelvåg", "kind": "village", "aliases": ["Kabelvag"]},
    {"country": "Norway", "canonical": "Ballstad", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Ramberg", "kind": "village", "aliases": []},
    {"country": "Norway", "canonical": "Å i Lofoten", "kind": "village", "aliases": ["A i Lofoten"]},
    {"country": "Norway", "canonical": "Harstad", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Sortland", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Stokmarknes", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Andenes", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Finnsnes", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Bardufoss", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Setermoen", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Kvaløya", "kind": "island", "aliases": ["Kvaloya"]},
    {"country": "Norway", "canonical": "Sommarøy", "kind": "island", "aliases": ["Sommaroy"]},
    {"country": "Norway", "canonical": "Lyngen", "kind": "region", "aliases": ["Lyngen Alps"]},
    {"country": "Norway", "canonical": "Skjervøy", "kind": "town", "aliases": ["Skjervoy"]},
    {"country": "Norway", "canonical": "Storslett", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Kautokeino", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Karasjok", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Hammerfest", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Lakselv", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Vardø", "kind": "town", "aliases": ["Vardo"]},
    {"country": "Norway", "canonical": "Vadsø", "kind": "town", "aliases": ["Vadso"]},
    {"country": "Norway", "canonical": "Båtsfjord", "kind": "town", "aliases": ["Batsfjord"]},
    {"country": "Norway", "canonical": "Berlevåg", "kind": "town", "aliases": ["Berlevag"]},
    {"country": "Norway", "canonical": "Mehamn", "kind": "town", "aliases": []},
    {"country": "Norway", "canonical": "Havøysund", "kind": "town", "aliases": ["Havoysund"]},
    {"country": "Norway", "canonical": "Øksfjord", "kind": "town", "aliases": ["Oksfjord"]},
    {"country": "Norway", "canonical": "Kjøllefjord", "kind": "town", "aliases": ["Kjollefjord"]},
    {"country": "Norway", "canonical": "Tana", "kind": "region", "aliases": []},
    {"country": "Norway", "canonical": "Varanger", "kind": "region", "aliases": ["Varanger Peninsula"]},

    # Finland
    {"country": "Finland", "canonical": "Helsinki", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Rovaniemi", "kind": "city", "aliases": ["Rovaneimi", "Rovaniem"]},
    {"country": "Finland", "canonical": "Turku", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Tampere", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Oulu", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Kuopio", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Jyväskylä", "kind": "city", "aliases": ["Jyvaskyla"]},
    {"country": "Finland", "canonical": "Lahti", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Vaasa", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Porvoo", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Rauma", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Savonlinna", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Lappeenranta", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Kuusamo", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Kemi", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Levi", "kind": "resort", "aliases": []},
    {"country": "Finland", "canonical": "Kittilä", "kind": "town", "aliases": ["Kittila"]},
    {"country": "Finland", "canonical": "Ivalo", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Inari", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Saariselkä", "kind": "resort", "aliases": ["Saariselka"]},
    {"country": "Finland", "canonical": "Kakslauttanen", "kind": "resort", "aliases": ["Kakslauttenen", "Kakslautanen"]},
    {"country": "Finland", "canonical": "Ylläs", "kind": "resort", "aliases": ["Yllas"]},
    {"country": "Finland", "canonical": "Pyhä", "kind": "resort", "aliases": ["Pyha"]},
    {"country": "Finland", "canonical": "Luosto", "kind": "resort", "aliases": []},
    {"country": "Finland", "canonical": "Ranua", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Åland", "kind": "region", "aliases": ["Aland", "Åland Islands", "Aland Islands"]},
    {"country": "Finland", "canonical": "Finnish Lapland", "kind": "region", "aliases": ["Lapland Finland", "Finland Lapland"]},
    {"country": "Finland", "canonical": "Finnish Lakeland", "kind": "region", "aliases": ["Lakeland Finland", "Lakeland"]},
    {"country": "Finland", "canonical": "Helsinki Airport", "kind": "airport", "aliases": ["Helsinki-Vantaa", "Helsinki Vantaa", "HEL"]},
    {"country": "Finland", "canonical": "Rovaniemi Airport", "kind": "airport", "aliases": ["RVN"]},
    {"country": "Finland", "canonical": "Ivalo Airport", "kind": "airport", "aliases": ["IVL"]},
    {"country": "Finland", "canonical": "Kittilä Airport", "kind": "airport", "aliases": ["Kittila Airport", "KTT"]},
    {"country": "Finland", "canonical": "Santa Claus Village", "kind": "attraction", "aliases": ["Santa Village", "Santa Claus Village Rovaniemi"]},
    {"country": "Finland", "canonical": "Arktikum", "kind": "attraction", "aliases": ["Arktikum Museum"]},
    {"country": "Finland", "canonical": "Suomenlinna", "kind": "attraction", "aliases": []},
    {"country": "Finland", "canonical": "Temppeliaukio Church", "kind": "attraction", "aliases": ["Rock Church"]},

    # Finland — expanded itinerary destinations, archipelago hubs, Lakeland gateways and Lapland resorts
    {"country": "Finland", "canonical": "Espoo", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Vantaa", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Kauniainen", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Kerava", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Järvenpää", "kind": "town", "aliases": ["Jarvenpaa"]},
    {"country": "Finland", "canonical": "Hyvinkää", "kind": "town", "aliases": ["Hyvinkaa"]},
    {"country": "Finland", "canonical": "Lohja", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Raseborg", "kind": "town", "aliases": ["Raasepori"]},
    {"country": "Finland", "canonical": "Tammisaari", "kind": "town", "aliases": ["Ekenäs", "Ekenas"]},
    {"country": "Finland", "canonical": "Hanko", "kind": "town", "aliases": ["Hangö", "Hango"]},
    {"country": "Finland", "canonical": "Fiskars", "kind": "village", "aliases": ["Fiskars Village"]},
    {"country": "Finland", "canonical": "Inkoo", "kind": "town", "aliases": ["Ingå", "Inga"]},
    {"country": "Finland", "canonical": "Kotka", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Hamina", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Kouvola", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Hämeenlinna", "kind": "city", "aliases": ["Hameenlinna"]},
    {"country": "Finland", "canonical": "Riihimäki", "kind": "town", "aliases": ["Riihimaki"]},
    {"country": "Finland", "canonical": "Forssa", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Naantali", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Salo", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Uusikaupunki", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Pori", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Kokkola", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Pietarsaari", "kind": "town", "aliases": ["Jakobstad"]},
    {"country": "Finland", "canonical": "Seinäjoki", "kind": "city", "aliases": ["Seinajoki"]},
    {"country": "Finland", "canonical": "Mariehamn", "kind": "town", "aliases": ["Maarianhamina"]},
    {"country": "Finland", "canonical": "Pargas", "kind": "town", "aliases": ["Parainen"]},
    {"country": "Finland", "canonical": "Nagu", "kind": "village", "aliases": ["Nauvo"]},
    {"country": "Finland", "canonical": "Korpo", "kind": "village", "aliases": ["Korppoo"]},
    {"country": "Finland", "canonical": "Kimitoön", "kind": "island", "aliases": ["Kimitoon", "Kemiönsaari", "Kemionsaari"]},
    {"country": "Finland", "canonical": "Utö", "kind": "island", "aliases": ["Uto", "Utö Finland", "Uto Finland"]},
    {"country": "Finland", "canonical": "Bengtskär", "kind": "island", "aliases": ["Bengtskar", "Bengtskär Lighthouse", "Bengtskar Lighthouse"]},
    {"country": "Finland", "canonical": "Kökar", "kind": "island", "aliases": ["Kokar"]},
    {"country": "Finland", "canonical": "Archipelago Sea", "kind": "region", "aliases": ["Finnish Archipelago", "Turku Archipelago"]},
    {"country": "Finland", "canonical": "Kvarken Archipelago", "kind": "region", "aliases": ["Kvarken", "Merenkurkku"]},
    {"country": "Finland", "canonical": "Hailuoto", "kind": "island", "aliases": []},
    {"country": "Finland", "canonical": "Mikkeli", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Imatra", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Joensuu", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Kajaani", "kind": "city", "aliases": []},
    {"country": "Finland", "canonical": "Iisalmi", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Nurmes", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Lieksa", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Koli", "kind": "village", "aliases": ["Koli Village"]},
    {"country": "Finland", "canonical": "Punkaharju", "kind": "village", "aliases": []},
    {"country": "Finland", "canonical": "Varkaus", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Jämsä", "kind": "town", "aliases": ["Jamsa"]},
    {"country": "Finland", "canonical": "Mänttä-Vilppula", "kind": "town", "aliases": ["Mantta-Vilppula", "Mänttä", "Mantta"]},
    {"country": "Finland", "canonical": "Orivesi", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Ylöjärvi", "kind": "town", "aliases": ["Ylojarvi"]},
    {"country": "Finland", "canonical": "Kangasala", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Vuokatti", "kind": "resort", "aliases": []},
    {"country": "Finland", "canonical": "Tahko", "kind": "resort", "aliases": ["Tahkovuori"]},
    {"country": "Finland", "canonical": "Himos", "kind": "resort", "aliases": []},
    {"country": "Finland", "canonical": "Messilä", "kind": "resort", "aliases": ["Messila"]},
    {"country": "Finland", "canonical": "Tornio", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Kemijärvi", "kind": "town", "aliases": ["Kemijarvi"]},
    {"country": "Finland", "canonical": "Sodankylä", "kind": "town", "aliases": ["Sodankyla"]},
    {"country": "Finland", "canonical": "Muonio", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Enontekiö", "kind": "town", "aliases": ["Enontekio"]},
    {"country": "Finland", "canonical": "Kilpisjärvi", "kind": "village", "aliases": ["Kilpisjarvi"]},
    {"country": "Finland", "canonical": "Hetta", "kind": "village", "aliases": ["Hetta Enontekiö", "Hetta Enontekio"]},
    {"country": "Finland", "canonical": "Kolari", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Äkäslompolo", "kind": "village", "aliases": ["Akaslompolo"]},
    {"country": "Finland", "canonical": "Pallas", "kind": "region", "aliases": ["Pallas Fell"]},
    {"country": "Finland", "canonical": "Salla", "kind": "resort", "aliases": ["Salla Finland"]},
    {"country": "Finland", "canonical": "Posio", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Savukoski", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Tankavaara", "kind": "village", "aliases": []},
    {"country": "Finland", "canonical": "Utsjoki", "kind": "town", "aliases": []},
    {"country": "Finland", "canonical": "Nuorgam", "kind": "village", "aliases": []},
    {"country": "Finland", "canonical": "Karigasniemi", "kind": "village", "aliases": []},
    {"country": "Finland", "canonical": "Nellim", "kind": "village", "aliases": []},
    {"country": "Finland", "canonical": "Sevettijärvi", "kind": "village", "aliases": ["Sevettijarvi"]},
    {"country": "Finland", "canonical": "Lemmenjoki", "kind": "region", "aliases": []},
    {"country": "Finland", "canonical": "Kiilopää", "kind": "resort", "aliases": ["Kiilopaa"]},
    {"country": "Finland", "canonical": "Ruka", "kind": "resort", "aliases": []},
    {"country": "Finland", "canonical": "Syöte", "kind": "resort", "aliases": ["Syote"]},
    {"country": "Finland", "canonical": "Iso-Syöte", "kind": "resort", "aliases": ["Iso Syöte", "Iso-Syote", "Iso Syote"]},
    {"country": "Finland", "canonical": "Nuuksio", "kind": "national_park", "aliases": ["Nuuksio National Park"]},
    {"country": "Finland", "canonical": "Sipoonkorpi", "kind": "national_park", "aliases": ["Sipoonkorpi National Park"]},
    {"country": "Finland", "canonical": "Repovesi", "kind": "national_park", "aliases": ["Repovesi National Park"]},
    {"country": "Finland", "canonical": "Koli National Park", "kind": "national_park", "aliases": ["Koli Kansallispuisto"]},
    {"country": "Finland", "canonical": "Linnansaari", "kind": "national_park", "aliases": ["Linnansaari National Park"]},
    {"country": "Finland", "canonical": "Oulanka", "kind": "national_park", "aliases": ["Oulanka National Park"]},
    {"country": "Finland", "canonical": "Urho Kekkonen", "kind": "national_park", "aliases": ["Urho Kekkonen National Park", "UKK National Park"]},
    {"country": "Finland", "canonical": "Pallas-Yllästunturi", "kind": "national_park", "aliases": ["Pallas-Yllastunturi", "Pallas-Yllästunturi National Park", "Pallas-Yllastunturi National Park"]},
    {"country": "Finland", "canonical": "Pyhä-Luosto", "kind": "national_park", "aliases": ["Pyha-Luosto", "Pyhä-Luosto National Park", "Pyha-Luosto National Park"]},
    {"country": "Finland", "canonical": "Lemmenjoki National Park", "kind": "national_park", "aliases": []},
    {"country": "Finland", "canonical": "Hossa", "kind": "national_park", "aliases": ["Hossa National Park"]},
    {"country": "Finland", "canonical": "Helvetinjärvi", "kind": "national_park", "aliases": ["Helvetinjarvi", "Helvetinjärvi National Park", "Helvetinjarvi National Park"]},
    {"country": "Finland", "canonical": "Leivonmäki", "kind": "national_park", "aliases": ["Leivonmaki", "Leivonmäki National Park", "Leivonmaki National Park"]},
    {"country": "Finland", "canonical": "Salamajärvi", "kind": "national_park", "aliases": ["Salamajarvi", "Salamajärvi National Park", "Salamajarvi National Park"]},
    {"country": "Finland", "canonical": "Archipelago National Park", "kind": "national_park", "aliases": ["Saaristomeri National Park"]},

    # Sweden
    {"country": "Sweden", "canonical": "Stockholm", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Gothenburg", "kind": "city", "aliases": ["Goteborg", "Göteborg", "Gothernburg", "Gothenbrug"]},
    {"country": "Sweden", "canonical": "Malmö", "kind": "city", "aliases": ["Malmo"]},
    {"country": "Sweden", "canonical": "Uppsala", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Västerås", "kind": "city", "aliases": ["Vasteras"]},
    {"country": "Sweden", "canonical": "Örebro", "kind": "city", "aliases": ["Orebro"]},
    {"country": "Sweden", "canonical": "Linköping", "kind": "city", "aliases": ["Linkoping"]},
    {"country": "Sweden", "canonical": "Norrköping", "kind": "city", "aliases": ["Norrkoping"]},
    {"country": "Sweden", "canonical": "Umeå", "kind": "city", "aliases": ["Umea"]},
    {"country": "Sweden", "canonical": "Luleå", "kind": "city", "aliases": ["Lulea"]},
    {"country": "Sweden", "canonical": "Kiruna", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Abisko", "kind": "village", "aliases": []},
    {"country": "Sweden", "canonical": "Jukkasjärvi", "kind": "village", "aliases": ["Jukkasjarvi"]},
    {"country": "Sweden", "canonical": "Boden", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Haparanda", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Åre", "kind": "resort", "aliases": ["Are"]},
    {"country": "Sweden", "canonical": "Visby", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Gotland", "kind": "island", "aliases": []},
    {"country": "Sweden", "canonical": "Öland", "kind": "island", "aliases": ["Oland"]},
    {"country": "Sweden", "canonical": "Swedish Lapland", "kind": "region", "aliases": ["Lapland Sweden", "Sweden Lapland"]},
    {"country": "Sweden", "canonical": "Stockholm Archipelago", "kind": "region", "aliases": []},
    {"country": "Sweden", "canonical": "West Sweden", "kind": "region", "aliases": []},
    {"country": "Sweden", "canonical": "Småland", "kind": "region", "aliases": ["Smaland"]},
    {"country": "Sweden", "canonical": "Dalarna", "kind": "region", "aliases": []},
    {"country": "Sweden", "canonical": "Gamla Stan", "kind": "attraction", "aliases": ["Stockholm Old Town"]},
    {"country": "Sweden", "canonical": "Vasa Museum", "kind": "attraction", "aliases": ["Vasamuseet"]},
    {"country": "Sweden", "canonical": "ABBA The Museum", "kind": "attraction", "aliases": ["ABBA Museum"]},
    {"country": "Sweden", "canonical": "Icehotel", "kind": "hotel", "aliases": ["Ice Hotel"]},
    {"country": "Sweden", "canonical": "Treehotel", "kind": "hotel", "aliases": ["Tree Hotel"]},
    {"country": "Sweden", "canonical": "Stockholm Airport", "kind": "airport", "aliases": ["Stockholm Arlanda", "Arlanda Airport", "ARN"]},
    {"country": "Sweden", "canonical": "Gothenburg Airport", "kind": "airport", "aliases": ["Göteborg Landvetter", "Goteborg Landvetter", "Landvetter Airport", "GOT"]},
    {"country": "Sweden", "canonical": "Kiruna Airport", "kind": "airport", "aliases": ["KRN"]},

    # Sweden — expanded itinerary destinations, archipelago hubs, Lapland gateways and rail/coastal stops
    {"country": "Sweden", "canonical": "Lund", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Helsingborg", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Jönköping", "kind": "city", "aliases": ["Jonkoping"]},
    {"country": "Sweden", "canonical": "Karlstad", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Gävle", "kind": "city", "aliases": ["Gavle"]},
    {"country": "Sweden", "canonical": "Sundsvall", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Östersund", "kind": "city", "aliases": ["Ostersund"]},
    {"country": "Sweden", "canonical": "Falun", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Borlänge", "kind": "town", "aliases": ["Borlange"]},
    {"country": "Sweden", "canonical": "Växjö", "kind": "city", "aliases": ["Vaxjo"]},
    {"country": "Sweden", "canonical": "Kalmar", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Karlskrona", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Halmstad", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Varberg", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Falkenberg", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Båstad", "kind": "town", "aliases": ["Bastad"]},
    {"country": "Sweden", "canonical": "Ängelholm", "kind": "town", "aliases": ["Angelholm"]},
    {"country": "Sweden", "canonical": "Ystad", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Simrishamn", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Kristianstad", "kind": "city", "aliases": []},
    {"country": "Sweden", "canonical": "Trelleborg", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Falsterbo", "kind": "village", "aliases": []},
    {"country": "Sweden", "canonical": "Kivik", "kind": "village", "aliases": []},
    {"country": "Sweden", "canonical": "Karlshamn", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Trollhättan", "kind": "town", "aliases": ["Trollhattan"]},
    {"country": "Sweden", "canonical": "Vänersborg", "kind": "town", "aliases": ["Vanersborg"]},
    {"country": "Sweden", "canonical": "Lidköping", "kind": "town", "aliases": ["Lidkoping"]},
    {"country": "Sweden", "canonical": "Skövde", "kind": "town", "aliases": ["Skovde"]},
    {"country": "Sweden", "canonical": "Gränna", "kind": "village", "aliases": ["Granna"]},
    {"country": "Sweden", "canonical": "Vadstena", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Eksjö", "kind": "town", "aliases": ["Eksjo"]},
    {"country": "Sweden", "canonical": "Vimmerby", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Sigtuna", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Mariefred", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Trosa", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Nyköping", "kind": "town", "aliases": ["Nykoping"]},
    {"country": "Sweden", "canonical": "Nynäshamn", "kind": "town", "aliases": ["Nynashamn"]},
    {"country": "Sweden", "canonical": "Vaxholm", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Sandhamn", "kind": "island", "aliases": []},
    {"country": "Sweden", "canonical": "Grinda", "kind": "island", "aliases": []},
    {"country": "Sweden", "canonical": "Utö", "kind": "island", "aliases": ["Uto"]},
    {"country": "Sweden", "canonical": "Marstrand", "kind": "island", "aliases": []},
    {"country": "Sweden", "canonical": "Lysekil", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Fjällbacka", "kind": "village", "aliases": ["Fjallbacka"]},
    {"country": "Sweden", "canonical": "Smögen", "kind": "village", "aliases": ["Smogen"]},
    {"country": "Sweden", "canonical": "Strömstad", "kind": "town", "aliases": ["Stromstad"]},
    {"country": "Sweden", "canonical": "Koster Islands", "kind": "island", "aliases": ["Kosteröarna", "Koster Islands Sweden", "Koster"]},
    {"country": "Sweden", "canonical": "Ven", "kind": "island", "aliases": ["Hven"]},
    {"country": "Sweden", "canonical": "Fårö", "kind": "island", "aliases": ["Faro", "Fårö Island"]},
    {"country": "Sweden", "canonical": "Tällberg", "kind": "village", "aliases": ["Tallberg"]},
    {"country": "Sweden", "canonical": "Mora", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Rättvik", "kind": "town", "aliases": ["Rattvik"]},
    {"country": "Sweden", "canonical": "Leksand", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Siljan", "kind": "region", "aliases": ["Lake Siljan"]},
    {"country": "Sweden", "canonical": "Sälen", "kind": "resort", "aliases": ["Salen"]},
    {"country": "Sweden", "canonical": "Idre", "kind": "resort", "aliases": ["Idre Fjäll", "Idre Fjall"]},
    {"country": "Sweden", "canonical": "Funäsdalen", "kind": "resort", "aliases": ["Funasdalen"]},
    {"country": "Sweden", "canonical": "Vemdalen", "kind": "resort", "aliases": []},
    {"country": "Sweden", "canonical": "Duved", "kind": "resort", "aliases": []},
    {"country": "Sweden", "canonical": "Riksgränsen", "kind": "resort", "aliases": ["Riksgransen"]},
    {"country": "Sweden", "canonical": "Björkliden", "kind": "resort", "aliases": ["Bjorkliden"]},
    {"country": "Sweden", "canonical": "Hemavan", "kind": "resort", "aliases": []},
    {"country": "Sweden", "canonical": "Tärnaby", "kind": "resort", "aliases": ["Tarnaby"]},
    {"country": "Sweden", "canonical": "Gällivare", "kind": "town", "aliases": ["Gallivare"]},
    {"country": "Sweden", "canonical": "Jokkmokk", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Arvidsjaur", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Arjeplog", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Sorsele", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Ammarnäs", "kind": "village", "aliases": ["Ammarnas"]},
    {"country": "Sweden", "canonical": "Kebnekaise", "kind": "region", "aliases": ["Kebnekaise Mountain"]},
    {"country": "Sweden", "canonical": "Kungsleden", "kind": "route", "aliases": ["King's Trail", "Kings Trail"]},
    {"country": "Sweden", "canonical": "Laponia", "kind": "region", "aliases": ["Laponian Area"]},
    {"country": "Sweden", "canonical": "Sarek", "kind": "national_park", "aliases": ["Sarek National Park"]},
    {"country": "Sweden", "canonical": "Padjelanta", "kind": "national_park", "aliases": ["Padjelanta National Park"]},
    {"country": "Sweden", "canonical": "Stora Sjöfallet", "kind": "national_park", "aliases": ["Stora Sjofallet", "Stora Sjöfallet National Park", "Stora Sjofallet National Park"]},
    {"country": "Sweden", "canonical": "Abisko National Park", "kind": "national_park", "aliases": ["Abisko Nationalpark"]},
    {"country": "Sweden", "canonical": "Fulufjället", "kind": "national_park", "aliases": ["Fulufjallet", "Fulufjället National Park", "Fulufjallet National Park"]},
    {"country": "Sweden", "canonical": "Tyresta", "kind": "national_park", "aliases": ["Tyresta National Park"]},
    {"country": "Sweden", "canonical": "Kosterhavet", "kind": "national_park", "aliases": ["Kosterhavet National Park"]},
    {"country": "Sweden", "canonical": "Tiveden", "kind": "national_park", "aliases": ["Tiveden National Park"]},
    {"country": "Sweden", "canonical": "Söderåsen", "kind": "national_park", "aliases": ["Soderasen", "Söderåsen National Park", "Soderasen National Park"]},
    {"country": "Sweden", "canonical": "Höga Kusten", "kind": "region", "aliases": ["High Coast", "High Coast Sweden"]},
    {"country": "Sweden", "canonical": "Örnsköldsvik", "kind": "town", "aliases": ["Ornskoldsvik"]},
    {"country": "Sweden", "canonical": "Härnösand", "kind": "town", "aliases": ["Harnosand"]},
    {"country": "Sweden", "canonical": "Hudiksvall", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Söderhamn", "kind": "town", "aliases": ["Soderhamn"]},
    {"country": "Sweden", "canonical": "Piteå", "kind": "town", "aliases": ["Pitea"]},
    {"country": "Sweden", "canonical": "Skellefteå", "kind": "city", "aliases": ["Skelleftea"]},
    {"country": "Sweden", "canonical": "Lycksele", "kind": "town", "aliases": []},
    {"country": "Sweden", "canonical": "Swedish Icehotel Region", "kind": "region", "aliases": ["Icehotel Region", "Jukkasjärvi Icehotel Region", "Jukkasjarvi Icehotel Region"]},

    # Iceland
    {"country": "Iceland", "canonical": "Reykjavík", "kind": "city", "aliases": ["Reykjavik", "Reykajvik", "Reykavik"]},
    {"country": "Iceland", "canonical": "Keflavík", "kind": "town", "aliases": ["Keflavik"]},
    {"country": "Iceland", "canonical": "Akureyri", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Vík", "kind": "village", "aliases": ["Vik", "Vík í Mýrdal", "Vik i Myrdal"]},
    {"country": "Iceland", "canonical": "Höfn", "kind": "town", "aliases": ["Hofn"]},
    {"country": "Iceland", "canonical": "Selfoss", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Húsavík", "kind": "town", "aliases": ["Husavik"]},
    {"country": "Iceland", "canonical": "Egilsstaðir", "kind": "town", "aliases": ["Egilsstadir"]},
    {"country": "Iceland", "canonical": "Ísafjörður", "kind": "town", "aliases": ["Isafjordur"]},
    {"country": "Iceland", "canonical": "Borgarnes", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Stykkishólmur", "kind": "town", "aliases": ["Stykkisholmur"]},
    {"country": "Iceland", "canonical": "Seyðisfjörður", "kind": "town", "aliases": ["Seydisfjordur"]},
    {"country": "Iceland", "canonical": "Golden Circle", "kind": "route", "aliases": []},
    {"country": "Iceland", "canonical": "South Coast", "kind": "region", "aliases": ["Iceland South Coast"]},
    {"country": "Iceland", "canonical": "Snæfellsnes", "kind": "region", "aliases": ["Snaefellsnes", "Snæfellsnes Peninsula", "Snaefellsnes Peninsula"]},
    {"country": "Iceland", "canonical": "Westfjords", "kind": "region", "aliases": ["West Fjords"]},
    {"country": "Iceland", "canonical": "Þingvellir National Park", "kind": "national_park", "aliases": ["Thingvellir", "Thingvellir National Park", "Þingvellir"]},
    {"country": "Iceland", "canonical": "Geysir", "kind": "attraction", "aliases": ["Geysir Geothermal Area"]},
    {"country": "Iceland", "canonical": "Gullfoss", "kind": "waterfall", "aliases": ["Gullfoss Waterfall"]},
    {"country": "Iceland", "canonical": "Kerið", "kind": "attraction", "aliases": ["Kerid", "Kerið Crater", "Kerid Crater"]},
    {"country": "Iceland", "canonical": "Blue Lagoon", "kind": "attraction", "aliases": ["Bluelagoon", "Blue lagoon"]},
    {"country": "Iceland", "canonical": "Sky Lagoon", "kind": "attraction", "aliases": ["Skylagoon", "Sky lagoon"]},
    {"country": "Iceland", "canonical": "Jökulsárlón", "kind": "lagoon", "aliases": ["Jokulsarlon", "Jökulsárlón Glacier Lagoon", "Jokulsarlon Glacier Lagoon"]},
    {"country": "Iceland", "canonical": "Diamond Beach", "kind": "beach", "aliases": []},
    {"country": "Iceland", "canonical": "Reynisfjara", "kind": "beach", "aliases": ["Reynisfjara Black Sand Beach"]},
    {"country": "Iceland", "canonical": "Seljalandsfoss", "kind": "waterfall", "aliases": []},
    {"country": "Iceland", "canonical": "Skógafoss", "kind": "waterfall", "aliases": ["Skogafoss"]},
    {"country": "Iceland", "canonical": "Mývatn", "kind": "lake", "aliases": ["Myvatn", "Lake Mývatn", "Lake Myvatn"]},
    {"country": "Iceland", "canonical": "Dettifoss", "kind": "waterfall", "aliases": []},
    {"country": "Iceland", "canonical": "Goðafoss", "kind": "waterfall", "aliases": ["Godafoss"]},
    {"country": "Iceland", "canonical": "Vatnajökull", "kind": "national_park", "aliases": ["Vatnajokull", "Vatnajökull National Park", "Vatnajokull National Park"]},
    {"country": "Iceland", "canonical": "Skaftafell", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Landmannalaugar", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Keflavík Airport", "kind": "airport", "aliases": ["Keflavik Airport", "KEF"]},
    {"country": "Iceland", "canonical": "Reykjavík Airport", "kind": "airport", "aliases": ["Reykjavik Airport", "RKV"]},
    {"country": "Iceland", "canonical": "Akureyri Airport", "kind": "airport", "aliases": ["AEY"]},

    # Iceland — expanded itinerary destinations, ring-road hubs, highland gateways and cruise ports
    {"country": "Iceland", "canonical": "Capital Region", "kind": "region", "aliases": ["Reykjavik Capital Region", "Greater Reykjavik"]},
    {"country": "Iceland", "canonical": "Kópavogur", "kind": "town", "aliases": ["Kopavogur"]},
    {"country": "Iceland", "canonical": "Hafnarfjörður", "kind": "town", "aliases": ["Hafnarfjordur", "Hafnarfjoerdur"]},
    {"country": "Iceland", "canonical": "Garðabær", "kind": "town", "aliases": ["Gardabaer", "Gardabær"]},
    {"country": "Iceland", "canonical": "Mosfellsbær", "kind": "town", "aliases": ["Mosfellsbaer"]},
    {"country": "Iceland", "canonical": "Akranes", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Reykjanes Peninsula", "kind": "region", "aliases": ["Reykjanes"]},
    {"country": "Iceland", "canonical": "Grindavík", "kind": "town", "aliases": ["Grindavik"]},
    {"country": "Iceland", "canonical": "Garður", "kind": "town", "aliases": ["Gardur"]},
    {"country": "Iceland", "canonical": "Sandgerði", "kind": "town", "aliases": ["Sandgerdi"]},
    {"country": "Iceland", "canonical": "Vogar", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Krýsuvík", "kind": "region", "aliases": ["Krysuvik"]},
    {"country": "Iceland", "canonical": "Fagradalsfjall", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Gunnuhver", "kind": "attraction", "aliases": ["Gunnuhver Hot Springs"]},
    {"country": "Iceland", "canonical": "Kleifarvatn", "kind": "lake", "aliases": []},
    {"country": "Iceland", "canonical": "Hveragerði", "kind": "town", "aliases": ["Hveragerdi"]},
    {"country": "Iceland", "canonical": "Laugarvatn", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Flúðir", "kind": "town", "aliases": ["Fludir"]},
    {"country": "Iceland", "canonical": "Skálholt", "kind": "village", "aliases": ["Skalholt"]},
    {"country": "Iceland", "canonical": "Þjórsárdalur", "kind": "region", "aliases": ["Thjorsardalur"]},
    {"country": "Iceland", "canonical": "Hella", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Hvolsvöllur", "kind": "town", "aliases": ["Hvolsvollur"]},
    {"country": "Iceland", "canonical": "Þórsmörk", "kind": "region", "aliases": ["Thorsmork"]},
    {"country": "Iceland", "canonical": "Vestmannaeyjar", "kind": "island", "aliases": ["Westman Islands", "Vestmann Islands"]},
    {"country": "Iceland", "canonical": "Heimaey", "kind": "island", "aliases": []},
    {"country": "Iceland", "canonical": "Dyrhólaey", "kind": "attraction", "aliases": ["Dyrholaey"]},
    {"country": "Iceland", "canonical": "Þakgil", "kind": "region", "aliases": ["Thakgil"]},
    {"country": "Iceland", "canonical": "Kirkjubæjarklaustur", "kind": "village", "aliases": ["Kirkjubaejarklaustur", "Klaustur"]},
    {"country": "Iceland", "canonical": "Fjaðrárgljúfur", "kind": "attraction", "aliases": ["Fjadrargljufur"]},
    {"country": "Iceland", "canonical": "Eldhraun", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Öræfi", "kind": "region", "aliases": ["Oraefi"]},
    {"country": "Iceland", "canonical": "Húsafell", "kind": "village", "aliases": ["Husafell"]},
    {"country": "Iceland", "canonical": "Reykholt", "kind": "village", "aliases": []},
    {"country": "Iceland", "canonical": "Hraunfossar", "kind": "waterfall", "aliases": ["Hraunfossar Waterfalls"]},
    {"country": "Iceland", "canonical": "Barnafoss", "kind": "waterfall", "aliases": []},
    {"country": "Iceland", "canonical": "Deildartunguhver", "kind": "attraction", "aliases": []},
    {"country": "Iceland", "canonical": "Arnarstapi", "kind": "village", "aliases": []},
    {"country": "Iceland", "canonical": "Hellnar", "kind": "village", "aliases": []},
    {"country": "Iceland", "canonical": "Búðir", "kind": "village", "aliases": ["Budir"]},
    {"country": "Iceland", "canonical": "Grundarfjörður", "kind": "town", "aliases": ["Grundarfjordur"]},
    {"country": "Iceland", "canonical": "Ólafsvík", "kind": "town", "aliases": ["Olafsvik"]},
    {"country": "Iceland", "canonical": "Hellissandur", "kind": "village", "aliases": []},
    {"country": "Iceland", "canonical": "Kirkjufell", "kind": "attraction", "aliases": ["Kirkjufell Mountain"]},
    {"country": "Iceland", "canonical": "Snæfellsjökull", "kind": "national_park", "aliases": ["Snaefellsjokull", "Snaefellsjokull National Park", "Snæfellsjökull National Park"]},
    {"country": "Iceland", "canonical": "Patreksfjörður", "kind": "town", "aliases": ["Patreksfjordur"]},
    {"country": "Iceland", "canonical": "Bíldudalur", "kind": "village", "aliases": ["Bildudalur"]},
    {"country": "Iceland", "canonical": "Tálknafjörður", "kind": "village", "aliases": ["Talknafjordur"]},
    {"country": "Iceland", "canonical": "Þingeyri", "kind": "village", "aliases": ["Thingeyri"]},
    {"country": "Iceland", "canonical": "Flateyri", "kind": "village", "aliases": []},
    {"country": "Iceland", "canonical": "Súðavík", "kind": "village", "aliases": ["Sudavik"]},
    {"country": "Iceland", "canonical": "Hólmavík", "kind": "town", "aliases": ["Holmavik"]},
    {"country": "Iceland", "canonical": "Drangsnes", "kind": "village", "aliases": []},
    {"country": "Iceland", "canonical": "Dynjandi", "kind": "waterfall", "aliases": ["Dynjandi Waterfall"]},
    {"country": "Iceland", "canonical": "Látrabjarg", "kind": "attraction", "aliases": ["Latrabjarg"]},
    {"country": "Iceland", "canonical": "Rauðasandur", "kind": "beach", "aliases": ["Raudasandur", "Raudisandur"]},
    {"country": "Iceland", "canonical": "Flatey", "kind": "island", "aliases": []},
    {"country": "Iceland", "canonical": "Hornstrandir", "kind": "national_park", "aliases": ["Hornstrandir Nature Reserve"]},
    {"country": "Iceland", "canonical": "Siglufjörður", "kind": "town", "aliases": ["Siglufjordur"]},
    {"country": "Iceland", "canonical": "Dalvík", "kind": "town", "aliases": ["Dalvik"]},
    {"country": "Iceland", "canonical": "Ólafsfjörður", "kind": "town", "aliases": ["Olafsfjordur"]},
    {"country": "Iceland", "canonical": "Sauðárkrókur", "kind": "town", "aliases": ["Saudarkrokur"]},
    {"country": "Iceland", "canonical": "Hofsós", "kind": "village", "aliases": ["Hofsos"]},
    {"country": "Iceland", "canonical": "Blönduós", "kind": "town", "aliases": ["Blonduos"]},
    {"country": "Iceland", "canonical": "Hvammstangi", "kind": "town", "aliases": []},
    {"country": "Iceland", "canonical": "Reykjahlíð", "kind": "village", "aliases": ["Reykjahlid"]},
    {"country": "Iceland", "canonical": "Skútustaðir", "kind": "village", "aliases": ["Skutustadir"]},
    {"country": "Iceland", "canonical": "Dimmuborgir", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Krafla", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Ásbyrgi", "kind": "national_park", "aliases": ["Asbyrgi"]},
    {"country": "Iceland", "canonical": "Jökulsárgljúfur", "kind": "national_park", "aliases": ["Jokulsargljufur"]},
    {"country": "Iceland", "canonical": "Grímsey", "kind": "island", "aliases": ["Grimsey"]},
    {"country": "Iceland", "canonical": "Eskifjörður", "kind": "town", "aliases": ["Eskifjordur"]},
    {"country": "Iceland", "canonical": "Neskaupstaður", "kind": "town", "aliases": ["Neskaupstadur"]},
    {"country": "Iceland", "canonical": "Reyðarfjörður", "kind": "town", "aliases": ["Reydarfjordur"]},
    {"country": "Iceland", "canonical": "Fáskrúðsfjörður", "kind": "town", "aliases": ["Faskrudsfjordur"]},
    {"country": "Iceland", "canonical": "Stöðvarfjörður", "kind": "village", "aliases": ["Stodvarfjordur"]},
    {"country": "Iceland", "canonical": "Djúpivogur", "kind": "town", "aliases": ["Djupivogur"]},
    {"country": "Iceland", "canonical": "Borgarfjörður Eystri", "kind": "village", "aliases": ["Borgarfjordur Eystri", "Bakkagerdi", "Bakkagerði"]},
    {"country": "Iceland", "canonical": "Vopnafjörður", "kind": "town", "aliases": ["Vopnafjordur"]},
    {"country": "Iceland", "canonical": "Hallormsstaður", "kind": "region", "aliases": ["Hallormsstadur"]},
    {"country": "Iceland", "canonical": "Hengifoss", "kind": "waterfall", "aliases": []},
    {"country": "Iceland", "canonical": "Stuðlagil", "kind": "attraction", "aliases": ["Studlagil", "Studlagil Canyon"]},
    {"country": "Iceland", "canonical": "Icelandic Highlands", "kind": "region", "aliases": ["Highlands of Iceland"]},
    {"country": "Iceland", "canonical": "Kerlingarfjöll", "kind": "region", "aliases": ["Kerlingarfjoll"]},
    {"country": "Iceland", "canonical": "Hveravellir", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Askja", "kind": "region", "aliases": []},
    {"country": "Iceland", "canonical": "Lakagígar", "kind": "region", "aliases": ["Laki", "Laki Craters", "Lakagigar"]},
    {"country": "Iceland", "canonical": "Kjölur", "kind": "route", "aliases": ["Kjalvegur", "Kjolur"]},
    {"country": "Iceland", "canonical": "Sprengisandur", "kind": "route", "aliases": []},
    {"country": "Iceland", "canonical": "Ring Road", "kind": "route", "aliases": ["Route 1", "Iceland Ring Road"]},
    {"country": "Iceland", "canonical": "Egilsstaðir Airport", "kind": "airport", "aliases": ["Egilsstadir Airport", "EGS"]},
    {"country": "Iceland", "canonical": "Ísafjörður Airport", "kind": "airport", "aliases": ["Isafjordur Airport", "IFJ"]},

    # Denmark
    {"country": "Denmark", "canonical": "Copenhagen", "kind": "city", "aliases": ["København", "Kobenhavn"]},
    {"country": "Denmark", "canonical": "Aarhus", "kind": "city", "aliases": ["Århus", "Arhus"]},
    {"country": "Denmark", "canonical": "Odense", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Aalborg", "kind": "city", "aliases": ["Ålborg", "Alborg"]},
    {"country": "Denmark", "canonical": "Billund", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Roskilde", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Helsingør", "kind": "town", "aliases": ["Helsingor", "Elsinore"]},
    {"country": "Denmark", "canonical": "Skagen", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Ribe", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Esbjerg", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Kolding", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Vejle", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Frederiksberg", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Bornholm", "kind": "island", "aliases": []},
    {"country": "Denmark", "canonical": "North Zealand", "kind": "region", "aliases": ["Nordsjælland", "Nordsjaelland"]},
    {"country": "Denmark", "canonical": "Funen", "kind": "island", "aliases": ["Fyn"]},
    {"country": "Denmark", "canonical": "Jutland", "kind": "region", "aliases": ["Jylland"]},
    {"country": "Denmark", "canonical": "Zealand", "kind": "island", "aliases": ["Sjælland", "Sjaelland"]},
    {"country": "Denmark", "canonical": "Tivoli Gardens", "kind": "attraction", "aliases": ["Tivoli"]},
    {"country": "Denmark", "canonical": "Nyhavn", "kind": "attraction", "aliases": []},
    {"country": "Denmark", "canonical": "Amalienborg", "kind": "attraction", "aliases": ["Amalienborg Palace"]},
    {"country": "Denmark", "canonical": "Christiansborg", "kind": "attraction", "aliases": ["Christiansborg Palace"]},
    {"country": "Denmark", "canonical": "Rosenborg Castle", "kind": "attraction", "aliases": ["Rosenborg"]},
    {"country": "Denmark", "canonical": "The Little Mermaid", "kind": "attraction", "aliases": ["Little Mermaid"]},
    {"country": "Denmark", "canonical": "Kronborg Castle", "kind": "attraction", "aliases": ["Kronborg"]},
    {"country": "Denmark", "canonical": "LEGOLAND Billund", "kind": "attraction", "aliases": ["Legoland", "Legoland Billund"]},
    {"country": "Denmark", "canonical": "Copenhagen Airport", "kind": "airport", "aliases": ["København Airport", "Kobenhavn Airport", "CPH", "Kastrup Airport"]},
    {"country": "Denmark", "canonical": "Billund Airport", "kind": "airport", "aliases": ["BLL"]},
    {"country": "Denmark", "canonical": "Aalborg Airport", "kind": "airport", "aliases": ["Aalborg Lufthavn", "Aalborg Airport", "AAL"]},


    # Denmark — expanded itinerary destinations, islands, coastal towns, rail hubs and cruise ports
    {"country": "Denmark", "canonical": "Dragør", "kind": "town", "aliases": ["Dragor"]},
    {"country": "Denmark", "canonical": "Køge", "kind": "town", "aliases": ["Koge"]},
    {"country": "Denmark", "canonical": "Næstved", "kind": "town", "aliases": ["Naestved"]},
    {"country": "Denmark", "canonical": "Slagelse", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Kalundborg", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Holbæk", "kind": "town", "aliases": ["Holbaek"]},
    {"country": "Denmark", "canonical": "Ringsted", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Sorø", "kind": "town", "aliases": ["Soro"]},
    {"country": "Denmark", "canonical": "Stevns", "kind": "region", "aliases": ["Stevns Klint Region"]},
    {"country": "Denmark", "canonical": "Stevns Klint", "kind": "attraction", "aliases": ["Stevns Cliff"]},
    {"country": "Denmark", "canonical": "Møn", "kind": "island", "aliases": ["Mon", "Moen"]},
    {"country": "Denmark", "canonical": "Møns Klint", "kind": "attraction", "aliases": ["Mons Klint", "Moens Klint"]},
    {"country": "Denmark", "canonical": "Lolland", "kind": "island", "aliases": []},
    {"country": "Denmark", "canonical": "Falster", "kind": "island", "aliases": []},
    {"country": "Denmark", "canonical": "Nykøbing Falster", "kind": "town", "aliases": ["Nykobing Falster"]},
    {"country": "Denmark", "canonical": "Maribo", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Nakskov", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Rødby", "kind": "town", "aliases": ["Rodby"]},
    {"country": "Denmark", "canonical": "Langeland", "kind": "island", "aliases": []},
    {"country": "Denmark", "canonical": "Ærø", "kind": "island", "aliases": ["Aero", "Aeroe"]},
    {"country": "Denmark", "canonical": "Ærøskøbing", "kind": "town", "aliases": ["Aeroskobing", "Aeroeskoebing"]},
    {"country": "Denmark", "canonical": "Svendborg", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Faaborg", "kind": "town", "aliases": ["Fåborg"]},
    {"country": "Denmark", "canonical": "Middelfart", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Nyborg", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Bogense", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Assens", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Kerteminde", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Samsø", "kind": "island", "aliases": ["Samso"]},
    {"country": "Denmark", "canonical": "Fanø", "kind": "island", "aliases": ["Fano"]},
    {"country": "Denmark", "canonical": "Mandø", "kind": "island", "aliases": ["Mando"]},
    {"country": "Denmark", "canonical": "Rømø", "kind": "island", "aliases": ["Romo"]},
    {"country": "Denmark", "canonical": "Tønder", "kind": "town", "aliases": ["Tonder"]},
    {"country": "Denmark", "canonical": "Sønderborg", "kind": "town", "aliases": ["Sonderborg"]},
    {"country": "Denmark", "canonical": "Aabenraa", "kind": "town", "aliases": ["Åbenrå", "Abenra", "Aabenra"]},
    {"country": "Denmark", "canonical": "Haderslev", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Fredericia", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Horsens", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Silkeborg", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Ry", "kind": "village", "aliases": []},
    {"country": "Denmark", "canonical": "Skanderborg", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Ebeltoft", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Grenaa", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Djursland", "kind": "region", "aliases": []},
    {"country": "Denmark", "canonical": "Mols Bjerge", "kind": "national_park", "aliases": ["Mols Bjerge National Park"]},
    {"country": "Denmark", "canonical": "Randers", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Viborg", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Herning", "kind": "city", "aliases": []},
    {"country": "Denmark", "canonical": "Ikast", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Holstebro", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Ringkøbing", "kind": "town", "aliases": ["Ringkobing"]},
    {"country": "Denmark", "canonical": "Hvide Sande", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Søndervig", "kind": "resort", "aliases": ["Sondervig"]},
    {"country": "Denmark", "canonical": "Lemvig", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Struer", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Thyborøn", "kind": "town", "aliases": ["Thyboron"]},
    {"country": "Denmark", "canonical": "Hanstholm", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Thisted", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Thy", "kind": "region", "aliases": ["Nationalpark Thy Region"]},
    {"country": "Denmark", "canonical": "National Park Thy", "kind": "national_park", "aliases": ["Thy National Park", "Nationalpark Thy"]},
    {"country": "Denmark", "canonical": "Mors", "kind": "island", "aliases": ["Mors Island"]},
    {"country": "Denmark", "canonical": "Nykøbing Mors", "kind": "town", "aliases": ["Nykobing Mors"]},
    {"country": "Denmark", "canonical": "Løgstør", "kind": "town", "aliases": ["Logstor"]},
    {"country": "Denmark", "canonical": "Hobro", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Mariager", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Rebild", "kind": "region", "aliases": ["Rebild Hills"]},
    {"country": "Denmark", "canonical": "Frederikshavn", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Sæby", "kind": "town", "aliases": ["Saeby"]},
    {"country": "Denmark", "canonical": "Hirtshals", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Løkken", "kind": "resort", "aliases": ["Lokken"]},
    {"country": "Denmark", "canonical": "Blokhus", "kind": "resort", "aliases": []},
    {"country": "Denmark", "canonical": "Lønstrup", "kind": "village", "aliases": ["Lonstrup"]},
    {"country": "Denmark", "canonical": "Rønne", "kind": "town", "aliases": ["Ronne"]},
    {"country": "Denmark", "canonical": "Svaneke", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Gudhjem", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Allinge", "kind": "town", "aliases": []},
    {"country": "Denmark", "canonical": "Nexø", "kind": "town", "aliases": ["Nexo"]},
    {"country": "Denmark", "canonical": "Christiansø", "kind": "island", "aliases": ["Christianso"]},
    {"country": "Denmark", "canonical": "Anholt", "kind": "island", "aliases": []},
    {"country": "Denmark", "canonical": "Læsø", "kind": "island", "aliases": ["Laeso"]},
    {"country": "Denmark", "canonical": "Wadden Sea National Park", "kind": "national_park", "aliases": ["Nationalpark Vadehavet", "Danish Wadden Sea"]},
    {"country": "Denmark", "canonical": "Kongernes Nordsjælland", "kind": "national_park", "aliases": ["Royal North Zealand National Park", "Nationalpark Kongernes Nordsjaelland"]},
    {"country": "Denmark", "canonical": "Aarhus Airport", "kind": "airport", "aliases": ["AAR", "Aarhus Lufthavn"]},
]

# Phrases that frequently appear in service cells but should never become
# destination names.
SERVICE_PHRASES = [
    "private hotel to airport",
    "private airport to hotel",
    "private hotel to station",
    "private station to hotel",
    "private transfer",
    "self transfer",
    "hotel to airport",
    "airport to hotel",
    "hotel to station",
    "station to hotel",
    "optional addon",
    "optional add on",
    "optional addons",
    "arrange day wise",
    "travel element",
    "shuttle / flybus",
    "shuttle flybus",
    "flybus",
    "city centre to airport",
    "city center to airport",
    "airport to city centre",
    "airport to city center",
]
