"""Public test group catalog constants."""

from .settings import (
    CHUNKED_GROUP_STAGE_SIZES,
    EMPTY_LEGACY_TEST_MODULES,
    PDF_STAGE_SIZE,
    REMAINING_STAGE_SIZE,
    TEST_ROOT,
    TIERED_STAGE_SIZE,
)
from .core import (
    ACTIVITY_TESTS,
    ARCHITECTURE_TESTS,
    CRITICAL_TESTS,
    FAST_TESTS,
    PARSER_TESTS,
)
from .quality import PDF_TESTS, QUALITY_TESTS, SLOW_TESTS, SLOW_TEST_SPLITS
from .ui_workflow import (
    CALCULATOR_TESTS,
    DAY_BRAIN_TESTS,
    EDITOR_TESTS,
    IMAGE_TESTS,
    STORAGE_TESTS,
    UI_TESTS,
    WORKFLOW_TESTS,
)
from .metadata import (
    CI_MATRIX_GROUPS,
    GROUP_DESCRIPTIONS,
    GROUP_ORDER,
    GROUPS,
    HEALTH_CHECK_GROUPS,
    RELEASE_CANDIDATE_GROUPS,
)

__all__ = (
    "TEST_ROOT",
    "EMPTY_LEGACY_TEST_MODULES",
    "REMAINING_STAGE_SIZE",
    "TIERED_STAGE_SIZE",
    "PDF_STAGE_SIZE",
    "CHUNKED_GROUP_STAGE_SIZES",
    "CRITICAL_TESTS",
    "FAST_TESTS",
    "PARSER_TESTS",
    "ACTIVITY_TESTS",
    "ARCHITECTURE_TESTS",
    "EDITOR_TESTS",
    "IMAGE_TESTS",
    "UI_TESTS",
    "DAY_BRAIN_TESTS",
    "QUALITY_TESTS",
    "PDF_TESTS",
    "CALCULATOR_TESTS",
    "STORAGE_TESTS",
    "WORKFLOW_TESTS",
    "SLOW_TESTS",
    "GROUPS",
    "GROUP_ORDER",
    "HEALTH_CHECK_GROUPS",
    "RELEASE_CANDIDATE_GROUPS",
    "CI_MATRIX_GROUPS",
    "GROUP_DESCRIPTIONS",
    "SLOW_TEST_SPLITS",
)
