"""Test-group data split out of scripts.test_groups.

Keep this package data-only; orchestration helpers stay in scripts.test_groups.
"""

from __future__ import annotations

CRITICAL_TESTS = (
    "tests/test_critical_feature_smoke.py",
    "tests/test_critical_workflow_contracts.py",
    "tests/test_failure_mode_regressions.py",
)

FAST_TESTS = (
    "tests/test_time_text_helpers.py",
    "tests/test_date_formatting.py",
    "tests/test_date_resolver.py",
    "tests/test_render_cache.py",
    "tests/test_commercial_status_helpers.py",
    "tests/test_normalizer_context_architecture.py",
    "tests/test_regressions_parser_normalizer.py",
    "tests/test_parser_normalizer_boundary.py",
    "tests/test_content_validator_scoping.py",
    "tests/test_leisure_arrival_metadata_cleanup.py",
    "tests/test_messy_transport_safety_net.py",
    "tests/test_structured_core_model.py",
    "tests/test_structured_core_model_validation.py",
    "tests/test_structured_html_source_identity.py",
    "tests/test_output_layout_contract.py",
    "tests/test_image_match_audit.py",
    "tests/test_text_cleanup_caching_regression.py",
    "tests/test_text_normalization_snapshots.py",
    "tests/test_hot_path_caching_regression.py",
    "tests/test_destination_image_delivery_regression.py",
    "tests/test_fixture_quality_polish.py",
)

PARSER_TESTS = (
    "tests/test_output_qa1_client_risk_quality.py",
    "tests/test_time_text_helpers.py",
    "tests/test_date_formatting.py",
    "tests/test_date_resolver.py",
    "tests/test_regressions_parser_normalizer.py",
    "tests/test_parser_normalizer_boundary.py",
    "tests/test_iceland_group_tour_parsing_regression.py",
    "tests/test_normalizer_context_architecture.py",
    "tests/test_parser_extractor_architecture_regression.py",
    "tests/test_norway_coastal_cruise_transfer_regression.py",
    "tests/test_train_details.py",
    "tests/test_commercial_status_helpers.py",
    "tests/test_content_validator_scoping.py",
    "tests/test_text_cleanup_caching_regression.py",
    "tests/test_supplier_review_workflow_regression.py",
    "tests/test_supplier_correction_workflow_regression.py",
    "tests/test_accept_supplier_corrections_regression.py",
    "tests/test_copy1_premium_day_intro_engine.py",    "tests/test_vipin_excel_corpus_runner_regression.py",
    "tests/test_vipin_messy_excel_rows_regression.py",
    "tests/test_corpus_driven_parser_fixes_regression.py",
    "tests/test_corpus_driven_hotel_parser_regression.py",
    "tests/test_qc_input_img_pdf_combined_regression.py",
    "tests/test_qc_input_pdf_style_image_regression.py",
    "tests/test_route_truth_precedence.py",

)

ACTIVITY_TESTS = (
    "tests/test_activity_compound_stress_fixtures.py",
    "tests/test_activity_cruise_classification.py",
    "tests/test_compound_experience_transport_timing.py",
    "tests/test_content_classification_priority.py",
    "tests/test_product_rule_registry.py",
    "tests/test_activity_training_catalogue_regression.py",
    "tests/test_activity_product_architecture_regression.py",
    "tests/test_activity_catalogue_and_qa_regression.py",
    "tests/test_source_fidelity_quality_gate.py",
    "tests/test_norway_source_fidelity_quality_gate.py",
    "tests/test_tallinn_excursion_wording_quality_gate.py",
    "tests/test_activity_product_fingerprints_quality_gate.py",
    "tests/test_activity_catalogue_hardening_quality_gate.py",
    "tests/test_warning_ui_and_icebreaker_fidelity_quality_gate.py",
    "tests/test_hot_path_caching_regression.py",
    "tests/test_title_safety_phase1.py",
    "tests/test_nutshell_cover_toolbar_regression.py",
    "tests/test_nutshell_fjordtours_regression.py",
    "tests/test_nutshell_characterization_regression.py",
    "tests/test_nutshell_domain_regression.py",
    "tests/test_nutshell_consumer_parity_regression.py",
    "tests/test_finland_source_fidelity_regression.py",
    "tests/test_reference_corpus_regression.py",
    "tests/test_group_tour_domain_regression.py",
    "tests/test_iceland_group_tour_parsing_regression.py",
    "tests/test_group_tour_rendering_regression.py",
)

ARCHITECTURE_TESTS = (
    "tests/test_bounded_test_catalogue_contract.py",
    "tests/test_architecture_report_fingerprints.py",
    "tests/test_patch19_sanitation_architecture.py",
    "tests/test_patch21_27_ownership_architecture.py",
    "tests/test_architecture_consolidation.py",
    "tests/test_foundation_cleanup_regression.py",
    "tests/test_cleanup_final_regression.py",
    "tests/test_real_excel_fixture_bank.py",
    "tests/test_architecture_guard_system.py",
    "tests/test_runtime_alignment.py",
    "tests/test_dead_code_packaging_regression.py",
    "tests/test_canonical_block_renderers.py",
    "tests/test_canonical_boundary.py",
    "tests/test_inclusion_exclusion_architecture.py",
    "tests/test_normalizer_context_architecture.py",
    "tests/test_output_layout_contract.py",
    "tests/test_quality_gate_architecture.py",
    "tests/test_render_document_source_of_truth.py",
    "tests/test_legacy_cleanup_regression_suite.py",
    "tests/test_structured_core_model.py",
    "tests/test_structured_core_model_validation.py",
    "tests/test_structured_html_source_identity.py",
    "tests/test_transport_model_architecture.py",
    "tests/test_wrapper_exports.py",
    "tests/test_lightweight_package_initializers.py",
    "tests/test_destination_registry_regression.py",
    "tests/test_norway_destination_expansion_regression.py",
    "tests/test_sweden_destination_expansion_regression.py",
    "tests/test_finland_destination_expansion_regression.py",
    "tests/test_denmark_destination_expansion_regression.py",
    "tests/test_iceland_destination_expansion_regression.py",
    "tests/test_content1_destination_copy_library.py",
    "tests/test_destination_copy_profiles3_regression.py",
    "tests/test_destination_image_profiles_visual_consistency.py",
    "tests/test_destination_route_journey_intelligence.py",
    "tests/test_destination_qc_and_pagination_regression.py",
    "tests/test_compatibility_facade_audit.py",
    "tests/test_test_runner_groups.py",
    "tests/test_resumable_test_orchestrator.py",
    "tests/test_streamlit_style_authority.py",
    "tests/test_calculator_layout_regression.py",
    "tests/test_editor_workflow_split_regression.py",
    "tests/test_style_registry_regression.py",
    "tests/test_architecture_boundaries_regression.py",
    "tests/test_nutshell_cover_toolbar_regression.py",
    "tests/test_nutshell_fjordtours_regression.py",
    "tests/test_nutshell_characterization_regression.py",
    "tests/test_nutshell_domain_regression.py",
    "tests/test_nutshell_consumer_parity_regression.py",
    "tests/test_correctness_diagnostics_regression.py",
    "tests/test_finland_source_fidelity_regression.py",
    "tests/test_reference_corpus_regression.py",
    "tests/test_group_tour_domain_regression.py",
    "tests/test_iceland_group_tour_parsing_regression.py",
    "tests/test_group_tour_rendering_regression.py",
    "tests/test_text_cleanup_caching_regression.py",
    "tests/test_text_cleanup_performance_regression.py",
    "tests/test_structural_cleanup_tools.py",
    "tests/test_arch_cleanup_facades.py",
    "tests/test_code_cleanup_hygiene_regression.py",
    "tests/test_repository_secret_policy.py",
    "tests/test_compatibility_deletion_boundary.py",
    "tests/test_generation_architecture_cleanup.py",
    "tests/test_parser_architecture_cleanup.py",
    "tests/test_parser_normalizer_boundary.py",
    "tests/test_workspace_debloat_regression.py",    "tests/test_legacy_cleanup_regression.py",
    "tests/test_pytest_marker_discipline.py",
    "tests/test_render_context_cache.py",
    "tests/test_itinerary_render_artifact_authority.py",
    "tests/test_visual_editor_render_document_authority.py",
    "tests/test_calculator_state_commit_boundary.py",
    "tests/test_calculator_frontend_namespace.py",
    "tests/test_calculator_library_transport.py",

)
