"""Test-group data split out of scripts.test_groups.

Keep this package data-only; orchestration helpers stay in scripts.test_groups.
"""

from __future__ import annotations

from .ui_workflow import DAY_BRAIN_TESTS

QUALITY_TESTS = (
    "tests/test_patch19_three_stage_sanitation.py",
    "tests/test_accommodation_wording.py",
    "tests/test_content_classification_priority.py",
    "tests/test_product_rule_registry.py",
    "tests/test_canonical_block_renderers.py",
    "tests/test_canonical_boundary.py",
    "tests/test_render_document_source_of_truth.py",
    "tests/test_inclusions_preview_accommodation_transport_followups.py",
    "tests/test_inclusion_exclusion_architecture.py",
    "tests/test_quality_gate_architecture.py",
    "tests/test_quality_ownership_boundary.py",
    "tests/test_client_copy_sanitation_contract.py",
    "tests/test_copy_sequence_authority.py",
    "tests/test_advisor_quality_gate_contract.py",
    "tests/test_itinerary_continuity_contract.py",
    "tests/test_day_state_arrival_contract.py",
    "tests/test_premium_optional_output.py",
    "tests/test_regressions_content_basics.py",
    "tests/test_regressions_transport_cruise.py",
    "tests/test_finland_transport_regressions.py",
    "tests/test_regressions_pdf_inclusions.py",
    "tests/test_output_quality_engine_regression.py",
    "tests/test_output_quality_and_images_regression.py",
    "tests/test_output_truth_contracts.py",
    "tests/test_extra_day_wrapper_rows.py",
    "tests/test_self_drive_truth_contract.py",
    "tests/test_enforcement_gaps_regression.py",
    *DAY_BRAIN_TESTS,
    "tests/test_image_bank_enforcement_regression.py",
    "tests/test_text_engine_consolidation_regression.py",
    "tests/test_reliability_diagnostics_regression.py",
    "tests/test_remote_image_bank_connector_regression.py",
    "tests/test_preview_pdf_group_tours_regression.py",
    "tests/test_client_sanitizer_default_images_regression.py",
    "tests/test_day_heading_dates.py",
    "tests/test_regressions_travel_text.py",
    "tests/test_correctness_diagnostics_regression.py",
    "tests/test_finland_source_fidelity_regression.py",
    "tests/test_reference_corpus_regression.py",
    "tests/test_group_tour_rendering_regression.py",
    "tests/test_content1_destination_copy_library.py",
    "tests/test_destination_copy_profiles3_regression.py",
    "tests/test_vipin_full_corpus_fixture.py",
    "tests/test_destination_route_journey_intelligence.py",
    "tests/test_destination_qc_and_pagination_regression.py",
    "tests/test_client_output_quality_regression.py",
    "tests/test_transport_domain_regression.py",
    "tests/test_transport_route_facts_authority.py",
    "tests/test_client_transport_wording_contract.py",
    "tests/test_transport_preview_quality_regression.py",
    "tests/test_transport_render_split.py",
    "tests/test_travel_sequence_and_day_fidelity_quality_gate.py",
    "tests/test_real_output_text_review.py",
    "tests/test_real_output_repetition_checks.py",
    "tests/test_real_output_quality_gate_norway_regression.py",
    "tests/test_real_output_quality_gate_norway_204_regression.py",
    "tests/test_real_output_quality_gate_iceland_regression.py",
    "tests/test_copy_decision_contracts.py",
    "tests/test_nordic_quality_sample.py",
    "tests/test_scandinavian_winter_quality_regressions.py",
    "tests/test_finland_messy_input_fidelity.py",
    "tests/test_group_tour_master_rows.py",
    "tests/test_accommodation_stress_fixtures.py",
    "tests/test_fixture_hardening_quality_gate.py",
    "tests/test_persistent_qa_report_quality_gate.py",
    "tests/test_source_fidelity_commercial_status_regression.py",
    "tests/test_corpus_driven_parser_fixes_regression.py",
    "tests/test_corpus_driven_hotel_parser_regression.py",
    "tests/test_vipin_excel_corpus_runner_regression.py",
    "tests/test_vipin_messy_excel_rows_regression.py",
    "tests/test_activity_training_fixture_hygiene.py",
    "tests/test_itinerary_name_baseline_regression.py",
    "tests/test_itinerary_stability_fidelity_repair.py",
    "tests/test_optional_commercial_safety.py",
    "tests/test_regressions_layout_preview.py",
    "tests/test_stress_logic_followups.py",

)

PDF_TESTS = (
    "tests/test_pdf_lazy_initialization_contract.py",
    "tests/test_sync_regression_suite1.py",
    "tests/test_pdf_render_model_regression.py",
    "tests/test_pdf6_luxury_proposal.py",
    "tests/test_pdf7_proposal_footer.py",
    "tests/test_pdf_export_fast_path.py",
    "tests/test_pdf_image_export_reliability.py",
    "tests/test_pdf_creation_flow_and_layout_cleanup.py",
    "tests/test_preview_pdf_parity.py",
    "tests/test_preview_pdf_parity_regression.py",
    "tests/test_regressions_pdf_inclusions.py",
    "tests/test_nutshell_cover_toolbar_regression.py",
    "tests/test_nutshell_fjordtours_regression.py",
    "tests/test_nutshell_consumer_parity_regression.py",
    "tests/test_correctness_diagnostics_regression.py",
    "tests/test_finland_source_fidelity_regression.py",
    "tests/test_group_tour_rendering_regression.py",
    "tests/test_premium_output_upgrade.py",
    "tests/test_premium_output_regression_followup.py",
    "tests/test_destination_image_profiles_visual_consistency.py",
    "tests/test_destination_route_journey_intelligence.py",
    "tests/test_destination_qc_and_pagination_regression.py",
    "tests/test_pdf8_luxury_day_layout.py",
    "tests/test_destination_copy_profiles3_regression.py",
    "tests/test_brand1_proposal_profiles.py",    "tests/test_booknordics_preview_pdf_parity_polish.py",
    "tests/test_pdf_day_layout_regression.py",
    "tests/test_pdf_editor_commit_gate.py",
    "tests/test_pdf_export_canva_like_flow.py",
    "tests/test_pdf_export_job_state.py",
    "tests/test_pdf_artifact_state.py",
    "tests/test_output_brand_theme.py",
    "tests/test_export_debloat_and_dm_sans.py",
    "tests/test_single_pipeline_brand_export_stability.py",
    "tests/test_export_readiness_ui.py",
    "tests/test_booknordics_cover_contrast_speed.py",
    "tests/test_pdf_commit_fast_delta.py",
    "tests/test_pdf_cover_page_shared.py",
    "tests/test_regressions_layout_preview.py",

)

SLOW_TESTS = (
    "tests/test_broad_logic_stress_regressions.py",
    "tests/test_pdf.py",
    "tests/test_real_fixture_quality_gate.py",
    "tests/test_regressions_fixture_quality.py",
    "tests/test_regressions_fixture_quality_transport.py",
    "tests/test_rendered_pdf_quality.py",
    "tests/test_self_drive_pdf_preview_parity.py",
)


REAL_FIXTURE_QUALITY_FILES = (
    "day_brain_edge_cases.txt",
    "finland_norway_autumn_alta.txt",
    "finland_norway_winter_family.txt",
    "finland_norway_winter_variant.txt",
    "finland_winter_quality_check.txt",
    "iceland_group_tour_summer_ring_road.txt",
    "iceland_group_tour_winter.txt",
    "iceland_hub_excursion_output_quality_regression.txt",
    "iceland_self_drive_summer.txt",
    "nordic_patch_ap_quality_input.txt",
    "nordic_quality_sample.txt",
    "norway_finland_family_autumn.txt",
    "norway_short_oslo_bergen_alesund.txt",
    "norway_sub_brain_sample.txt",
    "norway_sweden_denmark_summer.txt",
    "norway_winter_output_quality_regression.txt",
    "scandinavia_autumn_cruise.txt",
    "scandinavia_cruise_premium_working.txt",
    "sweden_lapland_latest_uploaded.txt",
)


def _real_fixture_check_name(filename: str) -> str:
    stem = filename.rsplit(".", 1)[0].replace("-", "_")
    return f"check_real_fixture_quality_{stem}"

SLOW_TEST_SPLITS = {
    "tests/test_real_fixture_quality_gate.py": tuple(
        _real_fixture_check_name(filename) for filename in REAL_FIXTURE_QUALITY_FILES
    ),
    "tests/test_regressions_fixture_quality.py": (
        "test_content_cleanup_for_helsinki_lapland_sample",
        "test_bad_input_contextual_travel_and_activity_cleanup",
        "test_korouoma_priority_keeps_thermal_and_barbecue",
        "test_self_guided_tallinn_is_not_labeled_guided",
        "test_generalized_iceland_self_drive_logic",
        "test_real_input_fixture_bank_core_expectations",
        "test_sweden_lapland_supplier_booking_information_not_in_client_inclusions",
    ),
    "tests/test_regressions_fixture_quality_transport.py": (
        "test_optional_arc_transfer_quality_gate",
        "test_clear_transport_wording_system",
        "test_real_uploaded_inputs_quality_gate",
    ),
}
