"""Test-group data split out of scripts.test_groups.

Keep this package data-only; orchestration helpers stay in scripts.test_groups.
"""

from __future__ import annotations

EDITOR_TESTS = (
    "tests/test_sync_regression_suite1.py",
    "tests/test_ready_for_client_workflow_regression.py",
    "tests/test_image_inspector_workflow_regression.py",
    "tests/test_editor_review_cleanup_contract.py",
    "tests/test_legacy_cleanup_regression_suite.py",
    "tests/test_actionable_review_center_regression.py",
    "tests/test_selection_refinement_regression.py",
    "tests/test_editor_preview_ownership_regression.py",
    "tests/test_editor_image_safety_regression.py",
    "tests/test_editor_section_safety_regression.py",
    "tests/test_editor_styling_regression.py",
    "tests/test_editor_workflow_split_regression.py",
    "tests/test_style_registry_regression.py",
    "tests/test_state_ownership_regression.py",
    "tests/test_persistent_draft_autosave_quality_gate.py",
    "tests/test_structured_html_source_identity.py",
    "tests/test_visual_editor_autosave_contract.py",
    "tests/test_visual_editor_frontend_recovery_contract.py",
    "tests/test_visual_editor_frontend_assets.py",
    "tests/test_visual_editor_typed_draft.py",
    "tests/test_nutshell_cover_toolbar_regression.py",
    "tests/test_nutshell_fjordtours_regression.py",
    "tests/test_nutshell_consumer_parity_regression.py",
    "tests/test_finland_source_fidelity_regression.py",
    "tests/test_group_tour_rendering_regression.py",
    "tests/test_client_readiness_export_gate_regression.py",    "tests/test_editor_block_inspector.py",
    "tests/test_editor_design_polish.py",
    "tests/test_editor_editing_coverage.py",
    "tests/test_editor_field_inspector.py",
    "tests/test_editor_layout_inspector.py",
    "tests/test_editor_manual_templates.py",
    "tests/test_editor_ordering_controls.py",
    "tests/test_editor_page_contract.py",
    "tests/test_editor_page_management.py",
    "tests/test_editor_readiness_panel.py",
    "tests/test_editor_save_recovery_polish.py",
    "tests/test_editor_sidebar_bloat_guards.py",
    "tests/test_editor_source_compare_restore.py",
    "tests/test_visual_editor_image_payload_cache.py",

)

IMAGE_TESTS = (
    "tests/test_app_image_bank_paths.py",
    "tests/test_image_bank_gateway_retry.py",
    "tests/test_image_match_audit.py",
    "tests/test_image_matcher_selection.py",
    "tests/test_image_matcher_selection_fallbacks.py",
    "tests/test_hot_path_caching_regression.py",
    "tests/test_destination_image_delivery_regression.py",
    "tests/test_image_bank_bootstrap_regression.py",
    "tests/test_image_bank_bootstrap_rollback_regression.py",
    "tests/test_add_pictures_workflow_regression.py",
    "tests/test_output_quality_and_images_regression.py",
    "tests/test_image_bank_enforcement_regression.py",
    "tests/test_remote_image_bank_connector_regression.py",
    "tests/test_client_sanitizer_default_images_regression.py",
    "tests/test_picture_destination_accommodation_quality_gate.py",
    "tests/test_nutshell_cover_toolbar_regression.py",
    "tests/test_nutshell_fjordtours_regression.py",
    "tests/test_southern_coastal_image_season_policy.py",
    "tests/test_destination_registry_regression.py",
    "tests/test_norway_destination_expansion_regression.py",
    "tests/test_sweden_destination_expansion_regression.py",
    "tests/test_finland_destination_expansion_regression.py",
    "tests/test_denmark_destination_expansion_regression.py",
    "tests/test_iceland_destination_expansion_regression.py",
    "tests/test_content1_destination_copy_library.py",
    "tests/test_destination_copy_profiles3_regression.py",
    "tests/test_destination_image_profiles_visual_consistency.py",
    "tests/test_destination_route_journey_intelligence.py",
    "tests/test_destination_qc_and_pagination_regression.py",
    "tests/test_image_qa1_service_aware_matching.py",
    "tests/test_itinerary_wide_image_assignment.py",    "tests/test_image_bank_shared_fallback_logic.py",
    "tests/test_image_bank_status_cache.py",
    "tests/test_picture_module_regressions.py",

)

UI_TESTS = (
    "tests/test_sync_regression_suite1.py",
    "tests/test_output_qa1_client_risk_quality.py",
    "tests/test_ready_for_client_workflow_regression.py",
    "tests/test_image_inspector_workflow_regression.py",
    "tests/test_editor_review_cleanup_contract.py",
    "tests/test_actionable_review_center_regression.py",
    "tests/test_selection_refinement_regression.py",
    "tests/test_legacy_ui_cleanup.py",
    "tests/test_dead_code_packaging_regression.py",
    "tests/test_regressions_ui_boundaries.py",
    "tests/test_ui_document_flow.py",
    "tests/test_ui_export_readiness.py",
    "tests/test_legacy_cleanup_regression_suite.py",
    "tests/test_ui_image_bank_gateway.py",
    "tests/test_ui_pdf_download_persistence.py",
    "tests/test_project_browser_and_downloads_regression.py",
    "tests/test_project_browser_state.py",
    "tests/test_ui_style_contrast.py",
    "tests/test_calculator_layout_regression.py",
    "tests/test_ui_workflow_shell.py",
    "tests/test_ui_workflow_state_actions.py",
    "tests/test_nutshell_cover_toolbar_regression.py",
    "tests/test_editor_workspace_polish.py",
    "tests/test_editor_interaction_polish.py",
    "tests/test_supplier_review_workflow_regression.py",
    "tests/test_supplier_correction_workflow_regression.py",
    "tests/test_accept_supplier_corrections_regression.py",
    "tests/test_premium_output_regression_followup.py",
    "tests/test_destination_image_profiles_visual_consistency.py",
    "tests/test_destination_route_journey_intelligence.py",
    "tests/test_destination_qc_and_pagination_regression.py",
    "tests/test_copy1_premium_day_intro_engine.py",
    "tests/test_client_readiness_export_gate_regression.py",
    "tests/test_brand1_proposal_profiles.py",    "tests/test_app_header_design_reset.py",
    "tests/test_design_system_regression.py",
    "tests/test_itinerary_health_report.py",
    "tests/test_loading_loop_recovery.py",
    "tests/test_project_file_ui_facade.py",
    "tests/test_scroll_regression.py",
    "tests/test_ui22_qc4_arc1_scroll_and_quality.py",
    "tests/test_generation_settings_and_preview_split.py",
    "tests/test_cover_background_selection.py",
    "tests/test_optimization_product_batch_foundation.py",

)

DAY_BRAIN_TESTS = (
    "tests/test_day_brain_copy.py",
    "tests/test_day_brain_intelligence.py",
    "tests/test_day_brain_proof_hardening.py",
    "tests/test_day_sub_brains.py",
)

CALCULATOR_TESTS = (
    "tests/test_calculator_backup_action.py",
    "tests/test_calculator_calculations.py",
    "tests/test_calculator_cleanup_state.py",
    "tests/test_calculator_component_mounting.py",
    "tests/test_calculator_component_payload.py",
    "tests/test_calculator_component_result.py",
    "tests/test_calculator_download_staleness.py",
    "tests/test_calculator_fetch_lines.py",
    "tests/test_calculator_formula_map.py",
    "tests/test_calculator_generation_action.py",
    "tests/test_calculator_grid_autocomplete.py",
    "tests/test_calculator_grid_values.py",
    "tests/test_calculator_library_cache.py",
    "tests/test_calculator_library_read_summary.py",
    "tests/test_calculator_library_search.py",
    "tests/test_calculator_library_seed_import.py",
    "tests/test_calculator_library_store.py",
    "tests/test_calculator_numeric_input.py",
    "tests/test_calculator_row_model.py",
    "tests/test_calculator_session_state.py",
    "tests/test_calculator_state.py",
    "tests/test_calculator_state_serialization.py",
    "tests/test_calculator_template_structure.py",
    "tests/test_calculator_to_itinerary_input.py",
    "tests/test_calculator_ui_foundation.py",
    "tests/test_calculator_layout_regression.py",
    "tests/test_calculator_workbook_export.py",
)

STORAGE_TESTS = (
    "tests/test_project_identity_state.py",
    "tests/test_project_storage_file_writer.py",
    "tests/test_project_storage_foundation.py",
    "tests/test_project_file_mvp_regression.py",
    "tests/test_current_edited_version_save_regression.py",
    "tests/test_saved_project_hardening_regression.py",
    "tests/test_project_browser_and_downloads_regression.py",
    "tests/test_project_browser_state.py",
    "tests/test_project_cloud_lifecycle_hardening.py",    "tests/test_backlog_storage_decision_regression.py",
    "tests/test_local_draft_delta_regression.py",
    "tests/test_saved_project_contract.py",
    "tests/test_saved_project_rebuild_path_regression.py",
    "tests/test_local_library_config_sources.py",
    "tests/test_local_library_editor.py",
    "tests/test_local_library_page_foundation.py",

)

WORKFLOW_TESTS = (
    "tests/test_workflow_reliability_regression.py",
    "tests/test_hosted_workflow_guardrails_regression.py",
    "tests/test_ui_workflow_shell.py",
    "tests/test_ui_workflow_state_actions.py",
    "tests/test_ui_export_readiness.py",
    "tests/test_ui_pdf_download_persistence.py",
    "tests/test_project_browser_and_downloads_regression.py",
    "tests/test_client_readiness_export_gate_regression.py",
    "tests/test_visual_editor_autosave_contract.py",
    "tests/test_visual_editor_frontend_recovery_contract.py",
    "tests/test_visual_editor_typed_draft.py",
    "tests/test_ci_workflow_guards.py",
    "tests/test_handoff_zip_workflow.py",
    "tests/test_workflow_debug_boundary_guards.py",
)
