// Loads responsibility-split visual editor scripts while keeping index.html thin.
[
  "editor_html_utils.js",
  "editor_save_state.js",
  "editor_scroll_state.js",
  "editor_local_draft.js",
  "editor_editable_markup.js",
  "editor_image_labels.js",
  "style_preset_data.js",
  "style_preset_lookup.js",
  "editor_block_templates.js",
  "editor_warning_model.js",
  "editor_debug_readiness.js",
  "editor_shell.js",
  "editor_render_summary.js",
  "editor_render_final_pages.js",
  "editor_document_outline.js",
  "editor_render_manual_pages.js",
  "editor_text_dom.js",
  "editor_text_history.js",
  "editor_text_selection.js",
  "editor_text_formatting.js",
  "editor_insert_blocks.js",
  "editor_paste_sanitizer.js",
  "editor_pages_model.js",
  "editor_blocks_model.js",
  "editor_selection_model.js",
  "editor_layout_overrides.js",
  "editor_manual_pages.js",
].forEach((scriptName) => {
  document.write(`<script src="js/${scriptName}"><\/script>`);
});
