"""Image helpers for the itinerary app."""

from .diagnostics import format_match_for_debug, get_image_bank_diagnostics, image_bank_debug_payload, image_bank_status_summary
from .image_bank import connect_remote_image_bank_if_missing, ensure_runtime_image_bank, ensure_runtime_image_bank_status, image_bank_status, image_bank_status_for_paths
from .fallback import _is_global_default_candidate, _score_default_candidate, is_global_default_candidate, score_default_candidate
from .matcher import (
    _candidate_destination_matches,
    _candidate_to_payload,
    _season_available_for_context,
    _select_best_candidate_for_context,
    build_day_context,
    candidate_destination_matches,
    candidate_to_payload,
    score_image_for_day,
    season_available_for_context,
    select_best_candidate_for_context,
    select_day_image,
    select_day_images,
)
from .image_match_audit import ImageAuditWarning, audit_day_image_match, audit_day_image_matches
from .metadata import (
    CITY_ALIASES,
    IMAGE_EXTENSIONS,
    SEASON_ALIASES,
    SUMMER_MONTHS,
    THEME_ALIASES,
    WINTER_MONTHS,
    ImageCandidate,
    city_variants,
    extract_image_metadata,
    infer_season_from_rows,
    infer_seasons,
    infer_themes,
    normalize_keyword,
    tokenize,
)
from .scanner import _coerce_image_bank_paths, coerce_image_bank_paths, scan_image_bank

__all__ = [
    "CITY_ALIASES",
    "IMAGE_EXTENSIONS",
    "SEASON_ALIASES",
    "SUMMER_MONTHS",
    "THEME_ALIASES",
    "WINTER_MONTHS",
    "ImageAuditWarning",
    "ImageCandidate",
    "_candidate_destination_matches",
    "_candidate_to_payload",
    "_coerce_image_bank_paths",
    "_is_global_default_candidate",
    "_score_default_candidate",
    "_season_available_for_context",
    "_select_best_candidate_for_context",
    "audit_day_image_match",
    "audit_day_image_matches",
    "build_day_context",
    "candidate_destination_matches",
    "candidate_to_payload",
    "city_variants",
    "connect_remote_image_bank_if_missing",
    "coerce_image_bank_paths",
    "extract_image_metadata",
    "ensure_runtime_image_bank",
    "ensure_runtime_image_bank_status",
    "format_match_for_debug",
    "get_image_bank_diagnostics",
    "image_bank_debug_payload",
    "image_bank_status",
    "image_bank_status_for_paths",
    "image_bank_status_summary",
    "infer_season_from_rows",
    "infer_seasons",
    "infer_themes",
    "is_global_default_candidate",
    "normalize_keyword",
    "scan_image_bank",
    "score_default_candidate",
    "score_image_for_day",
    "season_available_for_context",
    "select_best_candidate_for_context",
    "select_day_image",
    "select_day_images",
    "tokenize",
]
