"""Report test modules that are not covered by named validation groups."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.test_groups import GROUPS


def _normalize(path: object) -> str:
    return str(path).replace("\\", "/").lstrip("./")


def grouped_test_files() -> set[str]:
    files: set[str] = set()
    for group in GROUPS.values():
        for item in group:
            normalized = _normalize(item)
            if normalized.startswith("tests/") and normalized.endswith(".py"):
                files.add(normalized)
    return files


def duplicate_group_entries() -> dict[str, list[str]]:
    """Return test modules listed more than once in the same named group."""

    duplicates: dict[str, list[str]] = {}
    for group_name, group in GROUPS.items():
        seen: set[str] = set()
        repeated: list[str] = []
        for item in group:
            normalized = _normalize(item)
            if not (normalized.startswith("tests/") and normalized.endswith(".py")):
                continue
            if normalized in seen and normalized not in repeated:
                repeated.append(normalized)
            seen.add(normalized)
        if repeated:
            duplicates[group_name] = sorted(repeated)
    return duplicates


def all_test_files() -> set[str]:
    return {_normalize(path.relative_to(ROOT)) for path in (ROOT / "tests").glob("test_*.py")}


def build_report() -> dict[str, object]:
    all_files = all_test_files()
    grouped = grouped_test_files()
    full_only = sorted(all_files - grouped)
    stale_group_entries = sorted(path for path in grouped - all_files if path.startswith("tests/"))
    duplicates = duplicate_group_entries()
    return {
        "all_test_module_count": len(all_files),
        "grouped_test_module_count": len(grouped & all_files),
        "full_only_test_module_count": len(full_only),
        "stale_group_entry_count": len(stale_group_entries),
        "duplicate_group_entry_count": sum(len(items) for items in duplicates.values()),
        "full_only_test_modules": full_only,
        "stale_group_entries": stale_group_entries,
        "duplicate_group_entries": duplicates,
    }


def write_markdown(report: dict[str, object], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Test Group Hygiene Report",
        "",
        "Generated by `scripts/test_group_hygiene.py`.",
        "",
        f"* all test modules: {report['all_test_module_count']}",
        f"* grouped test modules: {report['grouped_test_module_count']}",
        f"* full-only test modules: {report['full_only_test_module_count']}",
        f"* stale group entries: {report['stale_group_entry_count']}",
        f"* duplicate group entries: {report['duplicate_group_entry_count']}",
        "",
        "## Full-only test modules",
        "",
    ]
    full_only = report["full_only_test_modules"]
    if isinstance(full_only, list) and full_only:
        lines.extend(f"* `{item}`" for item in full_only)
    else:
        lines.append("None.")
    lines.extend(["", "## Stale group entries", ""])
    stale = report["stale_group_entries"]
    if isinstance(stale, list) and stale:
        lines.extend(f"* `{item}`" for item in stale)
    else:
        lines.append("None.")
    lines.extend(["", "## Duplicate group entries", ""])
    duplicates = report["duplicate_group_entries"]
    if isinstance(duplicates, dict) and duplicates:
        for group_name, items in duplicates.items():
            lines.append(f"* `{group_name}`: " + ", ".join(f"`{item}`" for item in items))
    else:
        lines.append("None.")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json-output", type=Path, default=ROOT / "docs/reports/test_group_hygiene/latest.json")
    parser.add_argument("--markdown-output", type=Path, default=ROOT / "docs/reports/test_group_hygiene/latest.md")
    args = parser.parse_args()
    report = build_report()
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_markdown(report, args.markdown_output)
    print(f"Wrote {args.json_output}")
    print(f"Wrote {args.markdown_output}")
    print(
        f"test groups: grouped={report['grouped_test_module_count']}/{report['all_test_module_count']} "
        f"full_only={report['full_only_test_module_count']} stale={report['stale_group_entry_count']} "
        f"duplicates={report['duplicate_group_entry_count']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
