"""Denmark place aliases."""

from __future__ import annotations

DENMARK_PLACES = [{'country': 'Denmark', 'canonical': 'Copenhagen', 'kind': 'city', 'aliases': ['København', 'Kobenhavn']},
 {'country': 'Denmark', 'canonical': 'Aarhus', 'kind': 'city', 'aliases': ['Århus', 'Arhus']},
 {'country': 'Denmark', 'canonical': 'Odense', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Aalborg', 'kind': 'city', 'aliases': ['Ålborg', 'Alborg']},
 {'country': 'Denmark', 'canonical': 'Billund', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Roskilde', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Helsingør', 'kind': 'town', 'aliases': ['Helsingor', 'Elsinore']},
 {'country': 'Denmark', 'canonical': 'Skagen', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Ribe', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Esbjerg', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Kolding', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Vejle', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Frederiksberg', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Bornholm', 'kind': 'island', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'North Zealand', 'kind': 'region', 'aliases': ['Nordsjælland', 'Nordsjaelland']},
 {'country': 'Denmark', 'canonical': 'Funen', 'kind': 'island', 'aliases': ['Fyn']},
 {'country': 'Denmark', 'canonical': 'Jutland', 'kind': 'region', 'aliases': ['Jylland']},
 {'country': 'Denmark', 'canonical': 'Zealand', 'kind': 'island', 'aliases': ['Sjælland', 'Sjaelland']},
 {'country': 'Denmark', 'canonical': 'Tivoli Gardens', 'kind': 'attraction', 'aliases': ['Tivoli']},
 {'country': 'Denmark', 'canonical': 'Nyhavn', 'kind': 'attraction', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Amalienborg', 'kind': 'attraction', 'aliases': ['Amalienborg Palace']},
 {'country': 'Denmark', 'canonical': 'Christiansborg', 'kind': 'attraction', 'aliases': ['Christiansborg Palace']},
 {'country': 'Denmark', 'canonical': 'Rosenborg Castle', 'kind': 'attraction', 'aliases': ['Rosenborg']},
 {'country': 'Denmark', 'canonical': 'The Little Mermaid', 'kind': 'attraction', 'aliases': ['Little Mermaid']},
 {'country': 'Denmark', 'canonical': 'Kronborg Castle', 'kind': 'attraction', 'aliases': ['Kronborg']},
 {'country': 'Denmark',
  'canonical': 'LEGOLAND Billund',
  'kind': 'attraction',
  'aliases': ['Legoland', 'Legoland Billund']},
 {'country': 'Denmark',
  'canonical': 'Copenhagen Airport',
  'kind': 'airport',
  'aliases': ['København Airport', 'Kobenhavn Airport', 'CPH', 'Kastrup Airport']},
 {'country': 'Denmark', 'canonical': 'Billund Airport', 'kind': 'airport', 'aliases': ['BLL']},
 {'country': 'Denmark',
  'canonical': 'Aalborg Airport',
  'kind': 'airport',
  'aliases': ['Aalborg Lufthavn', 'Aalborg Airport', 'AAL']},
 {'country': 'Denmark', 'canonical': 'Dragør', 'kind': 'town', 'aliases': ['Dragor']},
 {'country': 'Denmark', 'canonical': 'Køge', 'kind': 'town', 'aliases': ['Koge']},
 {'country': 'Denmark', 'canonical': 'Næstved', 'kind': 'town', 'aliases': ['Naestved']},
 {'country': 'Denmark', 'canonical': 'Slagelse', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Kalundborg', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Holbæk', 'kind': 'town', 'aliases': ['Holbaek']},
 {'country': 'Denmark', 'canonical': 'Ringsted', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Sorø', 'kind': 'town', 'aliases': ['Soro']},
 {'country': 'Denmark', 'canonical': 'Stevns', 'kind': 'region', 'aliases': ['Stevns Klint Region']},
 {'country': 'Denmark', 'canonical': 'Stevns Klint', 'kind': 'attraction', 'aliases': ['Stevns Cliff']},
 {'country': 'Denmark', 'canonical': 'Møn', 'kind': 'island', 'aliases': ['Mon', 'Moen']},
 {'country': 'Denmark', 'canonical': 'Møns Klint', 'kind': 'attraction', 'aliases': ['Mons Klint', 'Moens Klint']},
 {'country': 'Denmark', 'canonical': 'Lolland', 'kind': 'island', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Falster', 'kind': 'island', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Nykøbing Falster', 'kind': 'town', 'aliases': ['Nykobing Falster']},
 {'country': 'Denmark', 'canonical': 'Maribo', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Nakskov', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Rødby', 'kind': 'town', 'aliases': ['Rodby']},
 {'country': 'Denmark', 'canonical': 'Langeland', 'kind': 'island', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Ærø', 'kind': 'island', 'aliases': ['Aero', 'Aeroe']},
 {'country': 'Denmark', 'canonical': 'Ærøskøbing', 'kind': 'town', 'aliases': ['Aeroskobing', 'Aeroeskoebing']},
 {'country': 'Denmark', 'canonical': 'Svendborg', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Faaborg', 'kind': 'town', 'aliases': ['Fåborg']},
 {'country': 'Denmark', 'canonical': 'Middelfart', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Nyborg', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Bogense', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Assens', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Kerteminde', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Samsø', 'kind': 'island', 'aliases': ['Samso']},
 {'country': 'Denmark', 'canonical': 'Fanø', 'kind': 'island', 'aliases': ['Fano']},
 {'country': 'Denmark', 'canonical': 'Mandø', 'kind': 'island', 'aliases': ['Mando']},
 {'country': 'Denmark', 'canonical': 'Rømø', 'kind': 'island', 'aliases': ['Romo']},
 {'country': 'Denmark', 'canonical': 'Tønder', 'kind': 'town', 'aliases': ['Tonder']},
 {'country': 'Denmark', 'canonical': 'Sønderborg', 'kind': 'town', 'aliases': ['Sonderborg']},
 {'country': 'Denmark', 'canonical': 'Aabenraa', 'kind': 'town', 'aliases': ['Åbenrå', 'Abenra', 'Aabenra']},
 {'country': 'Denmark', 'canonical': 'Haderslev', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Fredericia', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Horsens', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Silkeborg', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Ry', 'kind': 'village', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Skanderborg', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Ebeltoft', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Grenaa', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Djursland', 'kind': 'region', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Mols Bjerge', 'kind': 'national_park', 'aliases': ['Mols Bjerge National Park']},
 {'country': 'Denmark', 'canonical': 'Randers', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Viborg', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Herning', 'kind': 'city', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Ikast', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Holstebro', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Ringkøbing', 'kind': 'town', 'aliases': ['Ringkobing']},
 {'country': 'Denmark', 'canonical': 'Hvide Sande', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Søndervig', 'kind': 'resort', 'aliases': ['Sondervig']},
 {'country': 'Denmark', 'canonical': 'Lemvig', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Struer', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Thyborøn', 'kind': 'town', 'aliases': ['Thyboron']},
 {'country': 'Denmark', 'canonical': 'Hanstholm', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Thisted', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Thy', 'kind': 'region', 'aliases': ['Nationalpark Thy Region']},
 {'country': 'Denmark',
  'canonical': 'National Park Thy',
  'kind': 'national_park',
  'aliases': ['Thy National Park', 'Nationalpark Thy']},
 {'country': 'Denmark', 'canonical': 'Mors', 'kind': 'island', 'aliases': ['Mors Island']},
 {'country': 'Denmark', 'canonical': 'Nykøbing Mors', 'kind': 'town', 'aliases': ['Nykobing Mors']},
 {'country': 'Denmark', 'canonical': 'Løgstør', 'kind': 'town', 'aliases': ['Logstor']},
 {'country': 'Denmark', 'canonical': 'Hobro', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Mariager', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Rebild', 'kind': 'region', 'aliases': ['Rebild Hills']},
 {'country': 'Denmark', 'canonical': 'Frederikshavn', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Sæby', 'kind': 'town', 'aliases': ['Saeby']},
 {'country': 'Denmark', 'canonical': 'Hirtshals', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Løkken', 'kind': 'resort', 'aliases': ['Lokken']},
 {'country': 'Denmark', 'canonical': 'Blokhus', 'kind': 'resort', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Lønstrup', 'kind': 'village', 'aliases': ['Lonstrup']},
 {'country': 'Denmark', 'canonical': 'Rønne', 'kind': 'town', 'aliases': ['Ronne']},
 {'country': 'Denmark', 'canonical': 'Svaneke', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Gudhjem', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Allinge', 'kind': 'town', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Nexø', 'kind': 'town', 'aliases': ['Nexo']},
 {'country': 'Denmark', 'canonical': 'Christiansø', 'kind': 'island', 'aliases': ['Christianso']},
 {'country': 'Denmark', 'canonical': 'Anholt', 'kind': 'island', 'aliases': []},
 {'country': 'Denmark', 'canonical': 'Læsø', 'kind': 'island', 'aliases': ['Laeso']},
 {'country': 'Denmark',
  'canonical': 'Wadden Sea National Park',
  'kind': 'national_park',
  'aliases': ['Nationalpark Vadehavet', 'Danish Wadden Sea']},
 {'country': 'Denmark',
  'canonical': 'Kongernes Nordsjælland',
  'kind': 'national_park',
  'aliases': ['Royal North Zealand National Park', 'Nationalpark Kongernes Nordsjaelland']},
 {'country': 'Denmark', 'canonical': 'Aarhus Airport', 'kind': 'airport', 'aliases': ['AAR', 'Aarhus Lufthavn']}]
