"""Finland place aliases."""

from __future__ import annotations

FINLAND_PLACES = [{'country': 'Finland', 'canonical': 'Helsinki', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Rovaniemi', 'kind': 'city', 'aliases': ['Rovaneimi', 'Rovaniem']},
 {'country': 'Finland', 'canonical': 'Turku', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Tampere', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Oulu', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kuopio', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Jyväskylä', 'kind': 'city', 'aliases': ['Jyvaskyla']},
 {'country': 'Finland', 'canonical': 'Lahti', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Vaasa', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Porvoo', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Rauma', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Savonlinna', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Lappeenranta', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kuusamo', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kemi', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Levi', 'kind': 'resort', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kittilä', 'kind': 'town', 'aliases': ['Kittila']},
 {'country': 'Finland', 'canonical': 'Ivalo', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Inari', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Saariselkä', 'kind': 'resort', 'aliases': ['Saariselka']},
 {'country': 'Finland', 'canonical': 'Kakslauttanen', 'kind': 'resort', 'aliases': ['Kakslauttenen', 'Kakslautanen']},
 {'country': 'Finland', 'canonical': 'Ylläs', 'kind': 'resort', 'aliases': ['Yllas']},
 {'country': 'Finland', 'canonical': 'Pyhä', 'kind': 'resort', 'aliases': ['Pyha']},
 {'country': 'Finland', 'canonical': 'Luosto', 'kind': 'resort', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Ranua', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Åland', 'kind': 'region', 'aliases': ['Aland', 'Åland Islands', 'Aland Islands']},
 {'country': 'Finland',
  'canonical': 'Finnish Lapland',
  'kind': 'region',
  'aliases': ['Lapland Finland', 'Finland Lapland']},
 {'country': 'Finland', 'canonical': 'Finnish Lakeland', 'kind': 'region', 'aliases': ['Lakeland Finland', 'Lakeland']},
 {'country': 'Finland',
  'canonical': 'Helsinki Airport',
  'kind': 'airport',
  'aliases': ['Helsinki-Vantaa', 'Helsinki Vantaa', 'HEL']},
 {'country': 'Finland', 'canonical': 'Rovaniemi Airport', 'kind': 'airport', 'aliases': ['RVN']},
 {'country': 'Finland', 'canonical': 'Ivalo Airport', 'kind': 'airport', 'aliases': ['IVL']},
 {'country': 'Finland', 'canonical': 'Kittilä Airport', 'kind': 'airport', 'aliases': ['Kittila Airport', 'KTT']},
 {'country': 'Finland',
  'canonical': 'Santa Claus Village',
  'kind': 'attraction',
  'aliases': ['Santa Village', 'Santa Claus Village Rovaniemi']},
 {'country': 'Finland', 'canonical': 'Arktikum', 'kind': 'attraction', 'aliases': ['Arktikum Museum']},
 {'country': 'Finland', 'canonical': 'Suomenlinna', 'kind': 'attraction', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Temppeliaukio Church', 'kind': 'attraction', 'aliases': ['Rock Church']},
 {'country': 'Finland', 'canonical': 'Espoo', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Vantaa', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kauniainen', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kerava', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Järvenpää', 'kind': 'town', 'aliases': ['Jarvenpaa']},
 {'country': 'Finland', 'canonical': 'Hyvinkää', 'kind': 'town', 'aliases': ['Hyvinkaa']},
 {'country': 'Finland', 'canonical': 'Lohja', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Raseborg', 'kind': 'town', 'aliases': ['Raasepori']},
 {'country': 'Finland', 'canonical': 'Tammisaari', 'kind': 'town', 'aliases': ['Ekenäs', 'Ekenas']},
 {'country': 'Finland', 'canonical': 'Hanko', 'kind': 'town', 'aliases': ['Hangö', 'Hango']},
 {'country': 'Finland', 'canonical': 'Fiskars', 'kind': 'village', 'aliases': ['Fiskars Village']},
 {'country': 'Finland', 'canonical': 'Inkoo', 'kind': 'town', 'aliases': ['Ingå', 'Inga']},
 {'country': 'Finland', 'canonical': 'Kotka', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Hamina', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kouvola', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Hämeenlinna', 'kind': 'city', 'aliases': ['Hameenlinna']},
 {'country': 'Finland', 'canonical': 'Riihimäki', 'kind': 'town', 'aliases': ['Riihimaki']},
 {'country': 'Finland', 'canonical': 'Forssa', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Naantali', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Salo', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Uusikaupunki', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Pori', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kokkola', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Pietarsaari', 'kind': 'town', 'aliases': ['Jakobstad']},
 {'country': 'Finland', 'canonical': 'Seinäjoki', 'kind': 'city', 'aliases': ['Seinajoki']},
 {'country': 'Finland', 'canonical': 'Mariehamn', 'kind': 'town', 'aliases': ['Maarianhamina']},
 {'country': 'Finland', 'canonical': 'Pargas', 'kind': 'town', 'aliases': ['Parainen']},
 {'country': 'Finland', 'canonical': 'Nagu', 'kind': 'village', 'aliases': ['Nauvo']},
 {'country': 'Finland', 'canonical': 'Korpo', 'kind': 'village', 'aliases': ['Korppoo']},
 {'country': 'Finland',
  'canonical': 'Kimitoön',
  'kind': 'island',
  'aliases': ['Kimitoon', 'Kemiönsaari', 'Kemionsaari']},
 {'country': 'Finland', 'canonical': 'Utö', 'kind': 'island', 'aliases': ['Uto', 'Utö Finland', 'Uto Finland']},
 {'country': 'Finland',
  'canonical': 'Bengtskär',
  'kind': 'island',
  'aliases': ['Bengtskar', 'Bengtskär Lighthouse', 'Bengtskar Lighthouse']},
 {'country': 'Finland', 'canonical': 'Kökar', 'kind': 'island', 'aliases': ['Kokar']},
 {'country': 'Finland',
  'canonical': 'Archipelago Sea',
  'kind': 'region',
  'aliases': ['Finnish Archipelago', 'Turku Archipelago']},
 {'country': 'Finland', 'canonical': 'Kvarken Archipelago', 'kind': 'region', 'aliases': ['Kvarken', 'Merenkurkku']},
 {'country': 'Finland', 'canonical': 'Hailuoto', 'kind': 'island', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Mikkeli', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Imatra', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Joensuu', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kajaani', 'kind': 'city', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Iisalmi', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Nurmes', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Lieksa', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Koli', 'kind': 'village', 'aliases': ['Koli Village']},
 {'country': 'Finland', 'canonical': 'Punkaharju', 'kind': 'village', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Varkaus', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Jämsä', 'kind': 'town', 'aliases': ['Jamsa']},
 {'country': 'Finland',
  'canonical': 'Mänttä-Vilppula',
  'kind': 'town',
  'aliases': ['Mantta-Vilppula', 'Mänttä', 'Mantta']},
 {'country': 'Finland', 'canonical': 'Orivesi', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Ylöjärvi', 'kind': 'town', 'aliases': ['Ylojarvi']},
 {'country': 'Finland', 'canonical': 'Kangasala', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Vuokatti', 'kind': 'resort', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Tahko', 'kind': 'resort', 'aliases': ['Tahkovuori']},
 {'country': 'Finland', 'canonical': 'Himos', 'kind': 'resort', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Messilä', 'kind': 'resort', 'aliases': ['Messila']},
 {'country': 'Finland', 'canonical': 'Tornio', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kemijärvi', 'kind': 'town', 'aliases': ['Kemijarvi']},
 {'country': 'Finland', 'canonical': 'Sodankylä', 'kind': 'town', 'aliases': ['Sodankyla']},
 {'country': 'Finland', 'canonical': 'Muonio', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Enontekiö', 'kind': 'town', 'aliases': ['Enontekio']},
 {'country': 'Finland', 'canonical': 'Kilpisjärvi', 'kind': 'village', 'aliases': ['Kilpisjarvi']},
 {'country': 'Finland', 'canonical': 'Hetta', 'kind': 'village', 'aliases': ['Hetta Enontekiö', 'Hetta Enontekio']},
 {'country': 'Finland', 'canonical': 'Kolari', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Äkäslompolo', 'kind': 'village', 'aliases': ['Akaslompolo']},
 {'country': 'Finland', 'canonical': 'Pallas', 'kind': 'region', 'aliases': ['Pallas Fell']},
 {'country': 'Finland', 'canonical': 'Salla', 'kind': 'resort', 'aliases': ['Salla Finland']},
 {'country': 'Finland', 'canonical': 'Posio', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Savukoski', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Tankavaara', 'kind': 'village', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Utsjoki', 'kind': 'town', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Nuorgam', 'kind': 'village', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Karigasniemi', 'kind': 'village', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Nellim', 'kind': 'village', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Sevettijärvi', 'kind': 'village', 'aliases': ['Sevettijarvi']},
 {'country': 'Finland', 'canonical': 'Lemmenjoki', 'kind': 'region', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Kiilopää', 'kind': 'resort', 'aliases': ['Kiilopaa']},
 {'country': 'Finland', 'canonical': 'Ruka', 'kind': 'resort', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Syöte', 'kind': 'resort', 'aliases': ['Syote']},
 {'country': 'Finland', 'canonical': 'Iso-Syöte', 'kind': 'resort', 'aliases': ['Iso Syöte', 'Iso-Syote', 'Iso Syote']},
 {'country': 'Finland', 'canonical': 'Nuuksio', 'kind': 'national_park', 'aliases': ['Nuuksio National Park']},
 {'country': 'Finland', 'canonical': 'Sipoonkorpi', 'kind': 'national_park', 'aliases': ['Sipoonkorpi National Park']},
 {'country': 'Finland', 'canonical': 'Repovesi', 'kind': 'national_park', 'aliases': ['Repovesi National Park']},
 {'country': 'Finland',
  'canonical': 'Koli National Park',
  'kind': 'national_park',
  'aliases': ['Koli Kansallispuisto']},
 {'country': 'Finland', 'canonical': 'Linnansaari', 'kind': 'national_park', 'aliases': ['Linnansaari National Park']},
 {'country': 'Finland', 'canonical': 'Oulanka', 'kind': 'national_park', 'aliases': ['Oulanka National Park']},
 {'country': 'Finland',
  'canonical': 'Urho Kekkonen',
  'kind': 'national_park',
  'aliases': ['Urho Kekkonen National Park', 'UKK National Park']},
 {'country': 'Finland',
  'canonical': 'Pallas-Yllästunturi',
  'kind': 'national_park',
  'aliases': ['Pallas-Yllastunturi', 'Pallas-Yllästunturi National Park', 'Pallas-Yllastunturi National Park']},
 {'country': 'Finland',
  'canonical': 'Pyhä-Luosto',
  'kind': 'national_park',
  'aliases': ['Pyha-Luosto', 'Pyhä-Luosto National Park', 'Pyha-Luosto National Park']},
 {'country': 'Finland', 'canonical': 'Lemmenjoki National Park', 'kind': 'national_park', 'aliases': []},
 {'country': 'Finland', 'canonical': 'Hossa', 'kind': 'national_park', 'aliases': ['Hossa National Park']},
 {'country': 'Finland',
  'canonical': 'Helvetinjärvi',
  'kind': 'national_park',
  'aliases': ['Helvetinjarvi', 'Helvetinjärvi National Park', 'Helvetinjarvi National Park']},
 {'country': 'Finland',
  'canonical': 'Leivonmäki',
  'kind': 'national_park',
  'aliases': ['Leivonmaki', 'Leivonmäki National Park', 'Leivonmaki National Park']},
 {'country': 'Finland',
  'canonical': 'Salamajärvi',
  'kind': 'national_park',
  'aliases': ['Salamajarvi', 'Salamajärvi National Park', 'Salamajarvi National Park']},
 {'country': 'Finland',
  'canonical': 'Archipelago National Park',
  'kind': 'national_park',
  'aliases': ['Saaristomeri National Park']}]
