"""Iceland place aliases."""

from __future__ import annotations

ICELAND_PLACES = [{'country': 'Iceland', 'canonical': 'Reykjavík', 'kind': 'city', 'aliases': ['Reykjavik', 'Reykajvik', 'Reykavik']},
 {'country': 'Iceland', 'canonical': 'Keflavík', 'kind': 'town', 'aliases': ['Keflavik']},
 {'country': 'Iceland', 'canonical': 'Akureyri', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Vík', 'kind': 'village', 'aliases': ['Vik', 'Vík í Mýrdal', 'Vik i Myrdal']},
 {'country': 'Iceland', 'canonical': 'Höfn', 'kind': 'town', 'aliases': ['Hofn']},
 {'country': 'Iceland', 'canonical': 'Selfoss', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Húsavík', 'kind': 'town', 'aliases': ['Husavik']},
 {'country': 'Iceland', 'canonical': 'Egilsstaðir', 'kind': 'town', 'aliases': ['Egilsstadir']},
 {'country': 'Iceland', 'canonical': 'Ísafjörður', 'kind': 'town', 'aliases': ['Isafjordur']},
 {'country': 'Iceland', 'canonical': 'Borgarnes', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Stykkishólmur', 'kind': 'town', 'aliases': ['Stykkisholmur']},
 {'country': 'Iceland', 'canonical': 'Seyðisfjörður', 'kind': 'town', 'aliases': ['Seydisfjordur']},
 {'country': 'Iceland', 'canonical': 'Golden Circle', 'kind': 'route', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'South Coast', 'kind': 'region', 'aliases': ['Iceland South Coast']},
 {'country': 'Iceland',
  'canonical': 'Snæfellsnes',
  'kind': 'region',
  'aliases': ['Snaefellsnes', 'Snæfellsnes Peninsula', 'Snaefellsnes Peninsula']},
 {'country': 'Iceland', 'canonical': 'Westfjords', 'kind': 'region', 'aliases': ['West Fjords']},
 {'country': 'Iceland',
  'canonical': 'Þingvellir National Park',
  'kind': 'national_park',
  'aliases': ['Thingvellir', 'Thingvellir National Park', 'Þingvellir']},
 {'country': 'Iceland', 'canonical': 'Geysir', 'kind': 'attraction', 'aliases': ['Geysir Geothermal Area']},
 {'country': 'Iceland', 'canonical': 'Gullfoss', 'kind': 'waterfall', 'aliases': ['Gullfoss Waterfall']},
 {'country': 'Iceland',
  'canonical': 'Kerið',
  'kind': 'attraction',
  'aliases': ['Kerid', 'Kerið Crater', 'Kerid Crater']},
 {'country': 'Iceland', 'canonical': 'Blue Lagoon', 'kind': 'attraction', 'aliases': ['Bluelagoon', 'Blue lagoon']},
 {'country': 'Iceland', 'canonical': 'Sky Lagoon', 'kind': 'attraction', 'aliases': ['Skylagoon', 'Sky lagoon']},
 {'country': 'Iceland',
  'canonical': 'Jökulsárlón',
  'kind': 'lagoon',
  'aliases': ['Jokulsarlon', 'Jökulsárlón Glacier Lagoon', 'Jokulsarlon Glacier Lagoon']},
 {'country': 'Iceland', 'canonical': 'Diamond Beach', 'kind': 'beach', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Reynisfjara', 'kind': 'beach', 'aliases': ['Reynisfjara Black Sand Beach']},
 {'country': 'Iceland', 'canonical': 'Seljalandsfoss', 'kind': 'waterfall', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Skógafoss', 'kind': 'waterfall', 'aliases': ['Skogafoss']},
 {'country': 'Iceland', 'canonical': 'Mývatn', 'kind': 'lake', 'aliases': ['Myvatn', 'Lake Mývatn', 'Lake Myvatn']},
 {'country': 'Iceland', 'canonical': 'Dettifoss', 'kind': 'waterfall', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Goðafoss', 'kind': 'waterfall', 'aliases': ['Godafoss']},
 {'country': 'Iceland',
  'canonical': 'Vatnajökull',
  'kind': 'national_park',
  'aliases': ['Vatnajokull', 'Vatnajökull National Park', 'Vatnajokull National Park']},
 {'country': 'Iceland', 'canonical': 'Skaftafell', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Landmannalaugar', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Keflavík Airport', 'kind': 'airport', 'aliases': ['Keflavik Airport', 'KEF']},
 {'country': 'Iceland', 'canonical': 'Reykjavík Airport', 'kind': 'airport', 'aliases': ['Reykjavik Airport', 'RKV']},
 {'country': 'Iceland', 'canonical': 'Akureyri Airport', 'kind': 'airport', 'aliases': ['AEY']},
 {'country': 'Iceland',
  'canonical': 'Capital Region',
  'kind': 'region',
  'aliases': ['Reykjavik Capital Region', 'Greater Reykjavik']},
 {'country': 'Iceland', 'canonical': 'Kópavogur', 'kind': 'town', 'aliases': ['Kopavogur']},
 {'country': 'Iceland', 'canonical': 'Hafnarfjörður', 'kind': 'town', 'aliases': ['Hafnarfjordur', 'Hafnarfjoerdur']},
 {'country': 'Iceland', 'canonical': 'Garðabær', 'kind': 'town', 'aliases': ['Gardabaer', 'Gardabær']},
 {'country': 'Iceland', 'canonical': 'Mosfellsbær', 'kind': 'town', 'aliases': ['Mosfellsbaer']},
 {'country': 'Iceland', 'canonical': 'Akranes', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Reykjanes Peninsula', 'kind': 'region', 'aliases': ['Reykjanes']},
 {'country': 'Iceland', 'canonical': 'Grindavík', 'kind': 'town', 'aliases': ['Grindavik']},
 {'country': 'Iceland', 'canonical': 'Garður', 'kind': 'town', 'aliases': ['Gardur']},
 {'country': 'Iceland', 'canonical': 'Sandgerði', 'kind': 'town', 'aliases': ['Sandgerdi']},
 {'country': 'Iceland', 'canonical': 'Vogar', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Krýsuvík', 'kind': 'region', 'aliases': ['Krysuvik']},
 {'country': 'Iceland', 'canonical': 'Fagradalsfjall', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Gunnuhver', 'kind': 'attraction', 'aliases': ['Gunnuhver Hot Springs']},
 {'country': 'Iceland', 'canonical': 'Kleifarvatn', 'kind': 'lake', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Hveragerði', 'kind': 'town', 'aliases': ['Hveragerdi']},
 {'country': 'Iceland', 'canonical': 'Laugarvatn', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Flúðir', 'kind': 'town', 'aliases': ['Fludir']},
 {'country': 'Iceland', 'canonical': 'Skálholt', 'kind': 'village', 'aliases': ['Skalholt']},
 {'country': 'Iceland', 'canonical': 'Þjórsárdalur', 'kind': 'region', 'aliases': ['Thjorsardalur']},
 {'country': 'Iceland', 'canonical': 'Hella', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Hvolsvöllur', 'kind': 'town', 'aliases': ['Hvolsvollur']},
 {'country': 'Iceland', 'canonical': 'Þórsmörk', 'kind': 'region', 'aliases': ['Thorsmork']},
 {'country': 'Iceland',
  'canonical': 'Vestmannaeyjar',
  'kind': 'island',
  'aliases': ['Westman Islands', 'Vestmann Islands']},
 {'country': 'Iceland', 'canonical': 'Heimaey', 'kind': 'island', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Dyrhólaey', 'kind': 'attraction', 'aliases': ['Dyrholaey']},
 {'country': 'Iceland', 'canonical': 'Þakgil', 'kind': 'region', 'aliases': ['Thakgil']},
 {'country': 'Iceland',
  'canonical': 'Kirkjubæjarklaustur',
  'kind': 'village',
  'aliases': ['Kirkjubaejarklaustur', 'Klaustur']},
 {'country': 'Iceland', 'canonical': 'Fjaðrárgljúfur', 'kind': 'attraction', 'aliases': ['Fjadrargljufur']},
 {'country': 'Iceland', 'canonical': 'Eldhraun', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Öræfi', 'kind': 'region', 'aliases': ['Oraefi']},
 {'country': 'Iceland', 'canonical': 'Húsafell', 'kind': 'village', 'aliases': ['Husafell']},
 {'country': 'Iceland', 'canonical': 'Reykholt', 'kind': 'village', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Hraunfossar', 'kind': 'waterfall', 'aliases': ['Hraunfossar Waterfalls']},
 {'country': 'Iceland', 'canonical': 'Barnafoss', 'kind': 'waterfall', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Deildartunguhver', 'kind': 'attraction', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Arnarstapi', 'kind': 'village', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Hellnar', 'kind': 'village', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Búðir', 'kind': 'village', 'aliases': ['Budir']},
 {'country': 'Iceland', 'canonical': 'Grundarfjörður', 'kind': 'town', 'aliases': ['Grundarfjordur']},
 {'country': 'Iceland', 'canonical': 'Ólafsvík', 'kind': 'town', 'aliases': ['Olafsvik']},
 {'country': 'Iceland', 'canonical': 'Hellissandur', 'kind': 'village', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Kirkjufell', 'kind': 'attraction', 'aliases': ['Kirkjufell Mountain']},
 {'country': 'Iceland',
  'canonical': 'Snæfellsjökull',
  'kind': 'national_park',
  'aliases': ['Snaefellsjokull', 'Snaefellsjokull National Park', 'Snæfellsjökull National Park']},
 {'country': 'Iceland', 'canonical': 'Patreksfjörður', 'kind': 'town', 'aliases': ['Patreksfjordur']},
 {'country': 'Iceland', 'canonical': 'Bíldudalur', 'kind': 'village', 'aliases': ['Bildudalur']},
 {'country': 'Iceland', 'canonical': 'Tálknafjörður', 'kind': 'village', 'aliases': ['Talknafjordur']},
 {'country': 'Iceland', 'canonical': 'Þingeyri', 'kind': 'village', 'aliases': ['Thingeyri']},
 {'country': 'Iceland', 'canonical': 'Flateyri', 'kind': 'village', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Súðavík', 'kind': 'village', 'aliases': ['Sudavik']},
 {'country': 'Iceland', 'canonical': 'Hólmavík', 'kind': 'town', 'aliases': ['Holmavik']},
 {'country': 'Iceland', 'canonical': 'Drangsnes', 'kind': 'village', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Dynjandi', 'kind': 'waterfall', 'aliases': ['Dynjandi Waterfall']},
 {'country': 'Iceland', 'canonical': 'Látrabjarg', 'kind': 'attraction', 'aliases': ['Latrabjarg']},
 {'country': 'Iceland', 'canonical': 'Rauðasandur', 'kind': 'beach', 'aliases': ['Raudasandur', 'Raudisandur']},
 {'country': 'Iceland', 'canonical': 'Flatey', 'kind': 'island', 'aliases': []},
 {'country': 'Iceland',
  'canonical': 'Hornstrandir',
  'kind': 'national_park',
  'aliases': ['Hornstrandir Nature Reserve']},
 {'country': 'Iceland', 'canonical': 'Siglufjörður', 'kind': 'town', 'aliases': ['Siglufjordur']},
 {'country': 'Iceland', 'canonical': 'Dalvík', 'kind': 'town', 'aliases': ['Dalvik']},
 {'country': 'Iceland', 'canonical': 'Ólafsfjörður', 'kind': 'town', 'aliases': ['Olafsfjordur']},
 {'country': 'Iceland', 'canonical': 'Sauðárkrókur', 'kind': 'town', 'aliases': ['Saudarkrokur']},
 {'country': 'Iceland', 'canonical': 'Hofsós', 'kind': 'village', 'aliases': ['Hofsos']},
 {'country': 'Iceland', 'canonical': 'Blönduós', 'kind': 'town', 'aliases': ['Blonduos']},
 {'country': 'Iceland', 'canonical': 'Hvammstangi', 'kind': 'town', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Reykjahlíð', 'kind': 'village', 'aliases': ['Reykjahlid']},
 {'country': 'Iceland', 'canonical': 'Skútustaðir', 'kind': 'village', 'aliases': ['Skutustadir']},
 {'country': 'Iceland', 'canonical': 'Dimmuborgir', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Krafla', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Ásbyrgi', 'kind': 'national_park', 'aliases': ['Asbyrgi']},
 {'country': 'Iceland', 'canonical': 'Jökulsárgljúfur', 'kind': 'national_park', 'aliases': ['Jokulsargljufur']},
 {'country': 'Iceland', 'canonical': 'Grímsey', 'kind': 'island', 'aliases': ['Grimsey']},
 {'country': 'Iceland', 'canonical': 'Eskifjörður', 'kind': 'town', 'aliases': ['Eskifjordur']},
 {'country': 'Iceland', 'canonical': 'Neskaupstaður', 'kind': 'town', 'aliases': ['Neskaupstadur']},
 {'country': 'Iceland', 'canonical': 'Reyðarfjörður', 'kind': 'town', 'aliases': ['Reydarfjordur']},
 {'country': 'Iceland', 'canonical': 'Fáskrúðsfjörður', 'kind': 'town', 'aliases': ['Faskrudsfjordur']},
 {'country': 'Iceland', 'canonical': 'Stöðvarfjörður', 'kind': 'village', 'aliases': ['Stodvarfjordur']},
 {'country': 'Iceland', 'canonical': 'Djúpivogur', 'kind': 'town', 'aliases': ['Djupivogur']},
 {'country': 'Iceland',
  'canonical': 'Borgarfjörður Eystri',
  'kind': 'village',
  'aliases': ['Borgarfjordur Eystri', 'Bakkagerdi', 'Bakkagerði']},
 {'country': 'Iceland', 'canonical': 'Vopnafjörður', 'kind': 'town', 'aliases': ['Vopnafjordur']},
 {'country': 'Iceland', 'canonical': 'Hallormsstaður', 'kind': 'region', 'aliases': ['Hallormsstadur']},
 {'country': 'Iceland', 'canonical': 'Hengifoss', 'kind': 'waterfall', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Stuðlagil', 'kind': 'attraction', 'aliases': ['Studlagil', 'Studlagil Canyon']},
 {'country': 'Iceland', 'canonical': 'Icelandic Highlands', 'kind': 'region', 'aliases': ['Highlands of Iceland']},
 {'country': 'Iceland', 'canonical': 'Kerlingarfjöll', 'kind': 'region', 'aliases': ['Kerlingarfjoll']},
 {'country': 'Iceland', 'canonical': 'Hveravellir', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Askja', 'kind': 'region', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Lakagígar', 'kind': 'region', 'aliases': ['Laki', 'Laki Craters', 'Lakagigar']},
 {'country': 'Iceland', 'canonical': 'Kjölur', 'kind': 'route', 'aliases': ['Kjalvegur', 'Kjolur']},
 {'country': 'Iceland', 'canonical': 'Sprengisandur', 'kind': 'route', 'aliases': []},
 {'country': 'Iceland', 'canonical': 'Ring Road', 'kind': 'route', 'aliases': ['Route 1', 'Iceland Ring Road']},
 {'country': 'Iceland',
  'canonical': 'Egilsstaðir Airport',
  'kind': 'airport',
  'aliases': ['Egilsstadir Airport', 'EGS']},
 {'country': 'Iceland', 'canonical': 'Ísafjörður Airport', 'kind': 'airport', 'aliases': ['Isafjordur Airport', 'IFJ']}]
