"""Norway place aliases."""

from __future__ import annotations

NORWAY_PLACES = [{'country': 'Norway', 'canonical': 'Oslo', 'kind': 'city', 'aliases': ['Oslo City']},
 {'country': 'Norway', 'canonical': 'Bergen', 'kind': 'city', 'aliases': ['Bergent']},
 {'country': 'Norway', 'canonical': 'Tromsø', 'kind': 'city', 'aliases': ['Tromso', 'Tromsoe']},
 {'country': 'Norway', 'canonical': 'Trondheim', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Stavanger', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Ålesund', 'kind': 'city', 'aliases': ['Alesund', 'Aalesund']},
 {'country': 'Norway', 'canonical': 'Bodø', 'kind': 'city', 'aliases': ['Bodo', 'Bodoe']},
 {'country': 'Norway', 'canonical': 'Narvik', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Alta', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kirkenes', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Honningsvåg', 'kind': 'town', 'aliases': ['Honningsvag']},
 {'country': 'Norway', 'canonical': 'Longyearbyen', 'kind': 'town', 'aliases': []},
 {'country': 'Norway',
  'canonical': 'Svolvær',
  'kind': 'town',
  'aliases': ['Svolvaer', 'Svolaver', 'Svoalvaer', 'Svolvaerr']},
 {'country': 'Norway', 'canonical': 'Leknes', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Reine', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hamnøy', 'kind': 'village', 'aliases': ['Hamnoy']},
 {'country': 'Norway', 'canonical': 'Nusfjord', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Flåm', 'kind': 'village', 'aliases': ['Flam']},
 {'country': 'Norway', 'canonical': 'Myrdal', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Voss', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Gudvangen', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Geiranger', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Åndalsnes', 'kind': 'town', 'aliases': ['Andalsnes']},
 {'country': 'Norway', 'canonical': 'Molde', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kristiansand', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Tønsberg', 'kind': 'city', 'aliases': ['Tonsberg']},
 {'country': 'Norway', 'canonical': 'Drammen', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Fredrikstad', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lillehammer', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lofoten', 'kind': 'region', 'aliases': ['Lofoten Islands']},
 {'country': 'Norway', 'canonical': 'Senja', 'kind': 'island', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Vesterålen', 'kind': 'region', 'aliases': ['Vesteralen']},
 {'country': 'Norway', 'canonical': 'North Cape', 'kind': 'attraction', 'aliases': ['Nordkapp', 'North Cape Norway']},
 {'country': 'Norway', 'canonical': 'Svalbard', 'kind': 'region', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Oslofjord', 'kind': 'fjord', 'aliases': ['Oslo Fjord']},
 {'country': 'Norway', 'canonical': 'Sognefjord', 'kind': 'fjord', 'aliases': []},
 {'country': 'Norway',
  'canonical': 'Nærøyfjord',
  'kind': 'fjord',
  'aliases': ['Naeroyfjord', 'Nærøyfjorden', 'Naeroyfjorden']},
 {'country': 'Norway', 'canonical': 'Aurlandsfjord', 'kind': 'fjord', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hardangerfjord', 'kind': 'fjord', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Geirangerfjord', 'kind': 'fjord', 'aliases': ['Geirangerfjorden']},
 {'country': 'Norway', 'canonical': 'Lysefjord', 'kind': 'fjord', 'aliases': ['Lysefjorden']},
 {'country': 'Norway', 'canonical': 'Trollfjord', 'kind': 'fjord', 'aliases': ['Trollfjorden']},
 {'country': 'Norway', 'canonical': 'Preikestolen', 'kind': 'attraction', 'aliases': ['Pulpit Rock']},
 {'country': 'Norway', 'canonical': 'Kjerag', 'kind': 'attraction', 'aliases': ['Kjeragbolten']},
 {'country': 'Norway', 'canonical': 'Trolltunga', 'kind': 'attraction', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Bryggen', 'kind': 'attraction', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Fløibanen', 'kind': 'attraction', 'aliases': ['Floibanen', 'Fløien']},
 {'country': 'Norway',
  'canonical': 'Mount Fløyen',
  'kind': 'attraction',
  'aliases': ['Mt Fløyen', 'Mt Floyen', 'Mount Floyen', 'Fløyen', 'Floyen']},
 {'country': 'Norway', 'canonical': 'Fjellheisen', 'kind': 'attraction', 'aliases': []},
 {'country': 'Norway',
  'canonical': 'Flåm Railway',
  'kind': 'route',
  'aliases': ['Flam Railway', 'Flåmsbana', 'Flamsbana']},
 {'country': 'Norway',
  'canonical': 'Norway in a Nutshell',
  'kind': 'route',
  'aliases': ['Norway in a NUtshell', 'Norway in a Nutsheel', 'Norway in a Nutshel', 'Norway in a NUtsheel']},
 {'country': 'Norway',
  'canonical': 'Atlantic Road',
  'kind': 'route',
  'aliases': ['Atlanterhavsveien', 'Atlantic Ocean Road']},
 {'country': 'Norway',
  'canonical': 'Oslo Airport',
  'kind': 'airport',
  'aliases': ['Oslo Gardermoen', 'Gardermoen Airport', 'OSL']},
 {'country': 'Norway',
  'canonical': 'Bergen Airport',
  'kind': 'airport',
  'aliases': ['Bergen Flesland', 'Flesland Airport', 'BGO']},
 {'country': 'Norway',
  'canonical': 'Tromsø Airport',
  'kind': 'airport',
  'aliases': ['Tromso Airport', 'Tromsoe Airport', 'TOS']},
 {'country': 'Norway',
  'canonical': 'Svolvær Airport',
  'kind': 'airport',
  'aliases': ['Svolvaer Airport', 'Svolaver Airport', 'SVJ']},
 {'country': 'Norway',
  'canonical': 'Bodø Airport',
  'kind': 'airport',
  'aliases': ['Bodo Airport', 'Bodoe Airport', 'BOO']},
 {'country': 'Norway', 'canonical': 'Kirkenes Airport', 'kind': 'airport', 'aliases': ['KKN']},
 {'country': 'Norway', 'canonical': 'Hamar', 'kind': 'town', 'aliases': ['Mjøsbyen Hamar']},
 {'country': 'Norway', 'canonical': 'Gjøvik', 'kind': 'town', 'aliases': ['Gjovik']},
 {'country': 'Norway', 'canonical': 'Kongsvinger', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Eidsvoll', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lillestrøm', 'kind': 'city', 'aliases': ['Lillestrom']},
 {'country': 'Norway', 'canonical': 'Moss', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Sarpsborg', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Halden', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Horten', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Larvik', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Sandefjord', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Porsgrunn', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Skien', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Notodden', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Rjukan', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kragerø', 'kind': 'town', 'aliases': ['Kragero']},
 {'country': 'Norway', 'canonical': 'Risør', 'kind': 'town', 'aliases': ['Risor']},
 {'country': 'Norway', 'canonical': 'Arendal', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Grimstad', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lillesand', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Mandal', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Flekkefjord', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Farsund', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lyngdal', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Evje', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Setesdal', 'kind': 'region', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hovden', 'kind': 'resort', 'aliases': ['Hovden i Setesdal']},
 {'country': 'Norway', 'canonical': 'Sandnes', 'kind': 'city', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Sola', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Egersund', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Haugesund', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kopervik', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Skudeneshavn', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Utsira', 'kind': 'island', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Ryfylke', 'kind': 'region', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Sauda', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Jørpeland', 'kind': 'town', 'aliases': ['Jorpeland']},
 {'country': 'Norway', 'canonical': 'Tau', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Odda', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Eidfjord', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Ulvik', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Norheimsund', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Rosendal', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Balestrand', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lærdal', 'kind': 'village', 'aliases': ['Laerdal']},
 {'country': 'Norway', 'canonical': 'Aurland', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Undredal', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Solvorn', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kaupanger', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Finse', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Geilo', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Gol', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hemsedal', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Beitostølen', 'kind': 'resort', 'aliases': ['Beitostolen']},
 {'country': 'Norway', 'canonical': 'Fagernes', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Loen', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Olden', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Stryn', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Nordfjordeid', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Førde', 'kind': 'town', 'aliases': ['Forde']},
 {'country': 'Norway', 'canonical': 'Florø', 'kind': 'town', 'aliases': ['Floro']},
 {'country': 'Norway', 'canonical': 'Måløy', 'kind': 'town', 'aliases': ['Maloy']},
 {'country': 'Norway', 'canonical': 'Kalvåg', 'kind': 'village', 'aliases': ['Kalvag']},
 {'country': 'Norway', 'canonical': 'Stord', 'kind': 'island', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Bømlo', 'kind': 'island', 'aliases': ['Bomlo']},
 {'country': 'Norway', 'canonical': 'Fedje', 'kind': 'island', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Austevoll', 'kind': 'island', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kristiansund', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hellesylt', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Valldal', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Trollstigen', 'kind': 'route', 'aliases': ['Trollstigen Road']},
 {'country': 'Norway', 'canonical': 'Sunndalsøra', 'kind': 'town', 'aliases': ['Sunndalsora']},
 {'country': 'Norway', 'canonical': 'Surnadal', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hjørundfjord', 'kind': 'fjord', 'aliases': ['Hjorundfjord']},
 {'country': 'Norway', 'canonical': 'Romsdalen', 'kind': 'region', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Røros', 'kind': 'town', 'aliases': ['Roros']},
 {'country': 'Norway', 'canonical': 'Oppdal', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Stjørdal', 'kind': 'town', 'aliases': ['Stjordal']},
 {'country': 'Norway', 'canonical': 'Levanger', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Steinkjer', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Namsos', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Orkanger', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Dombås', 'kind': 'town', 'aliases': ['Dombas']},
 {'country': 'Norway', 'canonical': 'Otta', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lom', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Vågå', 'kind': 'village', 'aliases': ['Vaga']},
 {'country': 'Norway', 'canonical': 'Jotunheimen', 'kind': 'national_park', 'aliases': ['Jotunheimen National Park']},
 {'country': 'Norway', 'canonical': 'Rondane', 'kind': 'national_park', 'aliases': ['Rondane National Park']},
 {'country': 'Norway', 'canonical': 'Dovrefjell', 'kind': 'national_park', 'aliases': ['Dovrefjell National Park']},
 {'country': 'Norway',
  'canonical': 'Hardangervidda',
  'kind': 'national_park',
  'aliases': ['Hardangervidda National Park']},
 {'country': 'Norway',
  'canonical': 'Jostedalsbreen',
  'kind': 'national_park',
  'aliases': ['Jostedalsbreen National Park']},
 {'country': 'Norway', 'canonical': 'Folgefonna', 'kind': 'national_park', 'aliases': ['Folgefonna National Park']},
 {'country': 'Norway', 'canonical': 'Trysil', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hafjell', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kvitfjell', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Norefjell', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Rauland', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Gaustablikk', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Myrkdalen', 'kind': 'resort', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Vrådal', 'kind': 'resort', 'aliases': ['Vradal']},
 {'country': 'Norway', 'canonical': 'Brønnøysund', 'kind': 'town', 'aliases': ['Bronnoysund']},
 {'country': 'Norway', 'canonical': 'Sandnessjøen', 'kind': 'town', 'aliases': ['Sandnessjoen']},
 {'country': 'Norway', 'canonical': 'Mosjøen', 'kind': 'town', 'aliases': ['Mosjoen']},
 {'country': 'Norway', 'canonical': 'Mo i Rana', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Fauske', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Rognan', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Saltstraumen', 'kind': 'attraction', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kjerringøy', 'kind': 'village', 'aliases': ['Kjerringoy']},
 {'country': 'Norway', 'canonical': 'Vega', 'kind': 'island', 'aliases': ['Vega Islands']},
 {'country': 'Norway', 'canonical': 'Lovund', 'kind': 'island', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Træna', 'kind': 'island', 'aliases': ['Traena']},
 {'country': 'Norway', 'canonical': 'Dønna', 'kind': 'island', 'aliases': ['Donna']},
 {'country': 'Norway', 'canonical': 'Henningsvær', 'kind': 'village', 'aliases': ['Henningsvaer']},
 {'country': 'Norway', 'canonical': 'Kabelvåg', 'kind': 'village', 'aliases': ['Kabelvag']},
 {'country': 'Norway', 'canonical': 'Ballstad', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Ramberg', 'kind': 'village', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Å i Lofoten', 'kind': 'village', 'aliases': ['A i Lofoten']},
 {'country': 'Norway', 'canonical': 'Harstad', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Sortland', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Stokmarknes', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Andenes', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Finnsnes', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Bardufoss', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Setermoen', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kvaløya', 'kind': 'island', 'aliases': ['Kvaloya']},
 {'country': 'Norway', 'canonical': 'Sommarøy', 'kind': 'island', 'aliases': ['Sommaroy']},
 {'country': 'Norway', 'canonical': 'Lyngen', 'kind': 'region', 'aliases': ['Lyngen Alps']},
 {'country': 'Norway', 'canonical': 'Skjervøy', 'kind': 'town', 'aliases': ['Skjervoy']},
 {'country': 'Norway', 'canonical': 'Storslett', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Kautokeino', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Karasjok', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Hammerfest', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Lakselv', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Vardø', 'kind': 'town', 'aliases': ['Vardo']},
 {'country': 'Norway', 'canonical': 'Vadsø', 'kind': 'town', 'aliases': ['Vadso']},
 {'country': 'Norway', 'canonical': 'Båtsfjord', 'kind': 'town', 'aliases': ['Batsfjord']},
 {'country': 'Norway', 'canonical': 'Berlevåg', 'kind': 'town', 'aliases': ['Berlevag']},
 {'country': 'Norway', 'canonical': 'Mehamn', 'kind': 'town', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Havøysund', 'kind': 'town', 'aliases': ['Havoysund']},
 {'country': 'Norway', 'canonical': 'Øksfjord', 'kind': 'town', 'aliases': ['Oksfjord']},
 {'country': 'Norway', 'canonical': 'Kjøllefjord', 'kind': 'town', 'aliases': ['Kjollefjord']},
 {'country': 'Norway', 'canonical': 'Tana', 'kind': 'region', 'aliases': []},
 {'country': 'Norway', 'canonical': 'Varanger', 'kind': 'region', 'aliases': ['Varanger Peninsula']}]
