"""Sweden place aliases."""

from __future__ import annotations

SWEDEN_PLACES = [{'country': 'Sweden', 'canonical': 'Stockholm', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden',
  'canonical': 'Gothenburg',
  'kind': 'city',
  'aliases': ['Goteborg', 'Göteborg', 'Gothernburg', 'Gothenbrug']},
 {'country': 'Sweden', 'canonical': 'Malmö', 'kind': 'city', 'aliases': ['Malmo']},
 {'country': 'Sweden', 'canonical': 'Uppsala', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Västerås', 'kind': 'city', 'aliases': ['Vasteras']},
 {'country': 'Sweden', 'canonical': 'Örebro', 'kind': 'city', 'aliases': ['Orebro']},
 {'country': 'Sweden', 'canonical': 'Linköping', 'kind': 'city', 'aliases': ['Linkoping']},
 {'country': 'Sweden', 'canonical': 'Norrköping', 'kind': 'city', 'aliases': ['Norrkoping']},
 {'country': 'Sweden', 'canonical': 'Umeå', 'kind': 'city', 'aliases': ['Umea']},
 {'country': 'Sweden', 'canonical': 'Luleå', 'kind': 'city', 'aliases': ['Lulea']},
 {'country': 'Sweden', 'canonical': 'Kiruna', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Abisko', 'kind': 'village', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Jukkasjärvi', 'kind': 'village', 'aliases': ['Jukkasjarvi']},
 {'country': 'Sweden', 'canonical': 'Boden', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Haparanda', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Åre', 'kind': 'resort', 'aliases': ['Are']},
 {'country': 'Sweden', 'canonical': 'Visby', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Gotland', 'kind': 'island', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Öland', 'kind': 'island', 'aliases': ['Oland']},
 {'country': 'Sweden',
  'canonical': 'Swedish Lapland',
  'kind': 'region',
  'aliases': ['Lapland Sweden', 'Sweden Lapland']},
 {'country': 'Sweden', 'canonical': 'Stockholm Archipelago', 'kind': 'region', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'West Sweden', 'kind': 'region', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Småland', 'kind': 'region', 'aliases': ['Smaland']},
 {'country': 'Sweden', 'canonical': 'Dalarna', 'kind': 'region', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Gamla Stan', 'kind': 'attraction', 'aliases': ['Stockholm Old Town']},
 {'country': 'Sweden', 'canonical': 'Vasa Museum', 'kind': 'attraction', 'aliases': ['Vasamuseet']},
 {'country': 'Sweden', 'canonical': 'ABBA The Museum', 'kind': 'attraction', 'aliases': ['ABBA Museum']},
 {'country': 'Sweden', 'canonical': 'Icehotel', 'kind': 'hotel', 'aliases': ['Ice Hotel']},
 {'country': 'Sweden', 'canonical': 'Treehotel', 'kind': 'hotel', 'aliases': ['Tree Hotel']},
 {'country': 'Sweden',
  'canonical': 'Stockholm Airport',
  'kind': 'airport',
  'aliases': ['Stockholm Arlanda', 'Arlanda Airport', 'ARN']},
 {'country': 'Sweden',
  'canonical': 'Gothenburg Airport',
  'kind': 'airport',
  'aliases': ['Göteborg Landvetter', 'Goteborg Landvetter', 'Landvetter Airport', 'GOT']},
 {'country': 'Sweden', 'canonical': 'Kiruna Airport', 'kind': 'airport', 'aliases': ['KRN']},
 {'country': 'Sweden', 'canonical': 'Lund', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Helsingborg', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Jönköping', 'kind': 'city', 'aliases': ['Jonkoping']},
 {'country': 'Sweden', 'canonical': 'Karlstad', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Gävle', 'kind': 'city', 'aliases': ['Gavle']},
 {'country': 'Sweden', 'canonical': 'Sundsvall', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Östersund', 'kind': 'city', 'aliases': ['Ostersund']},
 {'country': 'Sweden', 'canonical': 'Falun', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Borlänge', 'kind': 'town', 'aliases': ['Borlange']},
 {'country': 'Sweden', 'canonical': 'Växjö', 'kind': 'city', 'aliases': ['Vaxjo']},
 {'country': 'Sweden', 'canonical': 'Kalmar', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Karlskrona', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Halmstad', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Varberg', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Falkenberg', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Båstad', 'kind': 'town', 'aliases': ['Bastad']},
 {'country': 'Sweden', 'canonical': 'Ängelholm', 'kind': 'town', 'aliases': ['Angelholm']},
 {'country': 'Sweden', 'canonical': 'Ystad', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Simrishamn', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Kristianstad', 'kind': 'city', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Trelleborg', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Falsterbo', 'kind': 'village', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Kivik', 'kind': 'village', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Karlshamn', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Trollhättan', 'kind': 'town', 'aliases': ['Trollhattan']},
 {'country': 'Sweden', 'canonical': 'Vänersborg', 'kind': 'town', 'aliases': ['Vanersborg']},
 {'country': 'Sweden', 'canonical': 'Lidköping', 'kind': 'town', 'aliases': ['Lidkoping']},
 {'country': 'Sweden', 'canonical': 'Skövde', 'kind': 'town', 'aliases': ['Skovde']},
 {'country': 'Sweden', 'canonical': 'Gränna', 'kind': 'village', 'aliases': ['Granna']},
 {'country': 'Sweden', 'canonical': 'Vadstena', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Eksjö', 'kind': 'town', 'aliases': ['Eksjo']},
 {'country': 'Sweden', 'canonical': 'Vimmerby', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Sigtuna', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Mariefred', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Trosa', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Nyköping', 'kind': 'town', 'aliases': ['Nykoping']},
 {'country': 'Sweden', 'canonical': 'Nynäshamn', 'kind': 'town', 'aliases': ['Nynashamn']},
 {'country': 'Sweden', 'canonical': 'Vaxholm', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Sandhamn', 'kind': 'island', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Grinda', 'kind': 'island', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Utö', 'kind': 'island', 'aliases': ['Uto', 'Utö Sweden', 'Uto Sweden']},
 {'country': 'Sweden', 'canonical': 'Marstrand', 'kind': 'island', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Lysekil', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Fjällbacka', 'kind': 'village', 'aliases': ['Fjallbacka']},
 {'country': 'Sweden', 'canonical': 'Smögen', 'kind': 'village', 'aliases': ['Smogen']},
 {'country': 'Sweden', 'canonical': 'Strömstad', 'kind': 'town', 'aliases': ['Stromstad']},
 {'country': 'Sweden',
  'canonical': 'Koster Islands',
  'kind': 'island',
  'aliases': ['Kosteröarna', 'Koster Islands Sweden', 'Koster']},
 {'country': 'Sweden', 'canonical': 'Ven', 'kind': 'island', 'aliases': ['Hven']},
 {'country': 'Sweden', 'canonical': 'Fårö', 'kind': 'island', 'aliases': ['Faro', 'Fårö Island']},
 {'country': 'Sweden', 'canonical': 'Tällberg', 'kind': 'village', 'aliases': ['Tallberg']},
 {'country': 'Sweden', 'canonical': 'Mora', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Rättvik', 'kind': 'town', 'aliases': ['Rattvik']},
 {'country': 'Sweden', 'canonical': 'Leksand', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Siljan', 'kind': 'region', 'aliases': ['Lake Siljan']},
 {'country': 'Sweden', 'canonical': 'Sälen', 'kind': 'resort', 'aliases': ['Salen']},
 {'country': 'Sweden', 'canonical': 'Idre', 'kind': 'resort', 'aliases': ['Idre Fjäll', 'Idre Fjall']},
 {'country': 'Sweden', 'canonical': 'Funäsdalen', 'kind': 'resort', 'aliases': ['Funasdalen']},
 {'country': 'Sweden', 'canonical': 'Vemdalen', 'kind': 'resort', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Duved', 'kind': 'resort', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Riksgränsen', 'kind': 'resort', 'aliases': ['Riksgransen']},
 {'country': 'Sweden', 'canonical': 'Björkliden', 'kind': 'resort', 'aliases': ['Bjorkliden']},
 {'country': 'Sweden', 'canonical': 'Hemavan', 'kind': 'resort', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Tärnaby', 'kind': 'resort', 'aliases': ['Tarnaby']},
 {'country': 'Sweden', 'canonical': 'Gällivare', 'kind': 'town', 'aliases': ['Gallivare']},
 {'country': 'Sweden', 'canonical': 'Jokkmokk', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Arvidsjaur', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Arjeplog', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Sorsele', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Ammarnäs', 'kind': 'village', 'aliases': ['Ammarnas']},
 {'country': 'Sweden', 'canonical': 'Kebnekaise', 'kind': 'region', 'aliases': ['Kebnekaise Mountain']},
 {'country': 'Sweden', 'canonical': 'Kungsleden', 'kind': 'route', 'aliases': ["King's Trail", 'Kings Trail']},
 {'country': 'Sweden', 'canonical': 'Laponia', 'kind': 'region', 'aliases': ['Laponian Area']},
 {'country': 'Sweden', 'canonical': 'Sarek', 'kind': 'national_park', 'aliases': ['Sarek National Park']},
 {'country': 'Sweden', 'canonical': 'Padjelanta', 'kind': 'national_park', 'aliases': ['Padjelanta National Park']},
 {'country': 'Sweden',
  'canonical': 'Stora Sjöfallet',
  'kind': 'national_park',
  'aliases': ['Stora Sjofallet', 'Stora Sjöfallet National Park', 'Stora Sjofallet National Park']},
 {'country': 'Sweden',
  'canonical': 'Abisko National Park',
  'kind': 'national_park',
  'aliases': ['Abisko Nationalpark']},
 {'country': 'Sweden',
  'canonical': 'Fulufjället',
  'kind': 'national_park',
  'aliases': ['Fulufjallet', 'Fulufjället National Park', 'Fulufjallet National Park']},
 {'country': 'Sweden', 'canonical': 'Tyresta', 'kind': 'national_park', 'aliases': ['Tyresta National Park']},
 {'country': 'Sweden', 'canonical': 'Kosterhavet', 'kind': 'national_park', 'aliases': ['Kosterhavet National Park']},
 {'country': 'Sweden', 'canonical': 'Tiveden', 'kind': 'national_park', 'aliases': ['Tiveden National Park']},
 {'country': 'Sweden',
  'canonical': 'Söderåsen',
  'kind': 'national_park',
  'aliases': ['Soderasen', 'Söderåsen National Park', 'Soderasen National Park']},
 {'country': 'Sweden', 'canonical': 'Höga Kusten', 'kind': 'region', 'aliases': ['High Coast', 'High Coast Sweden']},
 {'country': 'Sweden', 'canonical': 'Örnsköldsvik', 'kind': 'town', 'aliases': ['Ornskoldsvik']},
 {'country': 'Sweden', 'canonical': 'Härnösand', 'kind': 'town', 'aliases': ['Harnosand']},
 {'country': 'Sweden', 'canonical': 'Hudiksvall', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden', 'canonical': 'Söderhamn', 'kind': 'town', 'aliases': ['Soderhamn']},
 {'country': 'Sweden', 'canonical': 'Piteå', 'kind': 'town', 'aliases': ['Pitea']},
 {'country': 'Sweden', 'canonical': 'Skellefteå', 'kind': 'city', 'aliases': ['Skelleftea']},
 {'country': 'Sweden', 'canonical': 'Lycksele', 'kind': 'town', 'aliases': []},
 {'country': 'Sweden',
  'canonical': 'Swedish Icehotel Region',
  'kind': 'region',
  'aliases': ['Icehotel Region', 'Jukkasjärvi Icehotel Region', 'Jukkasjarvi Icehotel Region']}]
