"""Shared constants for composed client-facing activity descriptions."""

from __future__ import annotations

import re

TYPO_FIXES = [
    (r"\bTIckets\b", "Tickets"),
    (r"\bIncludese\b", "Includes"),
    (r"\bBrekafast\b", "Breakfast"),
    (r"\bSupeerior\b", "Superior"),
    (r"\bTallin\b", "Tallinn"),
    (r"\bROvaniemi\b", "Rovaniemi"),
    (r"\bKriuna\b", "Kiruna"),
    (r"\bExcurssion\b", "Excursion"),
]

RAW_OR_NON_PREMIUM_PATTERNS = [
    r"\|",
    r"\bwhat are you waiting for\b",
    r"\bcome and join us\b",
    r"\bstart your adventure\b",
    r"\bbook(?:ing)?\b",
    r"\bcheck availability\b",
    r"\bprice is per\b",
    r"\bplease note\b",
    r"\bparticipanter\b",
    r"\bcarried out\b",
    r"\bmin age\b",
    r"\bcancel(?:lation)?\b",
    r"\bat checkout\b",
    r"\binstagram\b",
    r"\byour guide will be timing you\b",
    r"\bthirsty\?\b",
    r"\bjust open your mouth\b",
    r"\binstant foot wetness\b",
    r"\bguaranteed\b",
    r"\bdesigned especially for those who wish\b",
    r"\bthe best rated\b",
    r"\baward-winning\b",
    r"\btripadvisor\b",
    r"\bviator\b",
    r"\bmarketing\b",
    r"\bwalking tour by citywalk\b",
]

GENERATED_INTRO_PATTERNS = [
    r"^A planned highlight brings you into",
    r"^Your main experience today is",
    r"^The day is shaped around",
    r"gives the day a clear focus",
    r"offering a well-paced way",
]

LANDMARKS: list[tuple[str, str]] = [
    ("Hvalfjörður fjords", r"Hvalfj[öo]r[ðd]ur"),
    ("Borgarfjörður", r"Borgarfj[öo]r[ðd]ur"),
    ("Reykholt", r"Reykholt"),
    ("Deildartunguhver", r"Deildartunguhver"),
    ("Hraunfossar", r"Hraunfossar"),
    ("Barnafoss", r"Barnafoss"),
    ("Snæfellsjökull", r"Sn[æa]fellsj[öo]kull"),
    ("Gerðuberg Cliff", r"Ger[ðd]uberg"),
    ("Ytri-Tunga", r"Ytri[- ]Tunga"),
    ("Arnarstapi", r"Arnarstapi"),
    ("Djúpalónssandur", r"Dj[úu]pal[óo]nssandur"),
    ("Kirkjufell", r"Kirkjufell"),
    ("Þingvellir National Park", r"(?:Þ|Th)ingvellir"),
    ("Geysir", r"\bGeysir\b"),
    ("Strokkur", r"Strokkur"),
    ("Gullfoss", r"Gullfoss"),
    ("Brúarfoss", r"Bruarfoss|Br[úu]arfoss"),
    ("Seljalandsfoss waterfall", r"Seljalandsfoss"),
    ("Gljúfrabúi", r"Glj[úu]frab[úu]i"),
    ("Skógafoss", r"Sk[óo]gafoss"),
    ("Reynisfjara", r"Reynisfjara"),
    ("Skaftafell", r"Skaftafell"),
    ("Vatnajökull", r"Vatnaj[öo]kull|Vatnajokull"),
    ("Jökulsárlón Glacier Lagoon", r"J[öo]kuls[áa]rl[óo]n|Jokulsarlon"),
    ("Diamond Beach", r"Diamond Beach"),
    ("Blue Ice Cave", r"blue ice cave|ice cave"),
    ("Fagradalsfjall", r"Fagradalsfjall|Geldingadalir"),
    ("Blue Lagoon", r"Blue Lagoon"),
    ("Hallgrímskirkja", r"Hallgr[íi]mskirkja"),
    ("Reykjavík landmarks", r"landmarks in Reykjav[íi]k|famous landmarks"),
    ("Reykjavík street art", r"street art"),
    ("Hauganes", r"Hauganes"),
    ("Eastfjords", r"Eastfjords"),
    ("Hallormsstaðaskógar", r"Hallormssta[ðd]ask[óo]gar"),
    ("Lake Lagafljót", r"Lagaflj[óo]t"),
    ("Dettifoss waterfall", r"Dettifoss"),
    ("Mývatn", r"M[ýy]vatn"),
    ("Námskarð", r"N[áa]mskar[ðd]"),
    ("Goðafoss waterfall", r"Go[ðd]afoss"),
    ("Lava Show Reykjavík", r"Lava Show"),
    ("Nuuksio National Park", r"Nuuksio"),
    ("Tallinn Old Town", r"Tallinn"),
    ("Stockholm Old Town", r"Stockholm.*Old Town|Old Town.*Stockholm|Gamla Stan"),
    ("Senate Square", r"Senate Square"),
    ("Santa Claus Village", r"Santa Claus Village"),
    ("Arktikum Museum", r"Arktikum"),
    ("Korouoma Canyon", r"Korouoma"),
    ("Polar Explorer Icebreaker", r"Polar Explorer|Icebreaker"),
    ("Bothnian Bay", r"Bothnian Bay"),
    ("Abisko", r"Abisko"),
    ("Mount Nuolja", r"Nuolja"),
    ("Aurora Sky Station", r"Aurora sky station"),
    ("Kiruna", r"Kiruna"),
    ("Munch Museum", r"Munch Museum"),
    ("Mostraumen", r"Mostraumen"),
    ("Mount Fløyen", r"Fl[øo]yen|Fl[øo]ibanen"),
    ("Nordmarka forests", r"Nordmarka"),
    ("Suomenlinna", r"Suomenlinna"),
    ("Helsinki Cathedral", r"Helsinki Cathedral"),
    ("Sibelius Monument", r"Sibelius"),
]

STOP_SOURCE_SECTION_RE = re.compile(
    r"(?:\n\s*|\s+-\s+)(?:What's included|What’s included|Included With|Includes?|Included|Highlights?|Stops|Please note|Booking Information|Not included|Not Included|Excludes?|Meeting Point|Pick up / meeting point|Pick-up / meeting point|Departure|Duration|Suitable for|Age limit|Gather at|Carried out|Participanter)\s*:?\b",
    re.I,
)


