"""Public compatibility facade for group-tour source enrichment."""

from itinerary_generation.group_tour_accommodation import add_group_tour_accommodation_rows, extract_group_tour_accommodation_stays
from itinerary_generation.group_tour_detection import is_group_tour_overview
from itinerary_generation.group_tour_optional_extras import annotate_group_tour_optional_extras, extract_optional_group_tour_extra_titles
from itinerary_generation.group_tour_supplier_titles import extract_supplier_day_title, supplier_day_number

__all__ = ["add_group_tour_accommodation_rows", "annotate_group_tour_optional_extras", "extract_group_tour_accommodation_stays", "extract_optional_group_tour_extra_titles", "extract_supplier_day_title", "is_group_tour_overview", "supplier_day_number"]
